blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/opendcl/community/discussions/new?category=q-a
    about: How-to and support for Studio, Runtime, and AutoLISP
  - name: Wishlist
    url: https://github.com/opendcl/community/discussions/new?category=ideas
    about: Request something OpenDCL cannot do today
