//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Editor.rc
//
#define IDAPPLY                         3
#define IDADD                           3
#define IDREGISTER                      3
#define IDDELETE                        5
#define IDUPDATE                        6
#define IDC_LISTBOX                     9
#define IDD_LISTDIALOG                  12
#define IDS_LSPFILENAME                 12
#define IDS_NAME                        13
#define IDS_EVENT                       14
#define IDS_SELECTPROJECTLISPFILE       15
#define IDS_TAB1                        17
#define IDS_TAB2                        18
#define IDS_TAB3                        19
#define IDS_ADD                         22
#define IDS_FILTER                      23
#define IDS_SAMPLENODE                  24
#define IDS_MASKED                      28
#define IDS_PROPERTYWIZARD              29
#define IDI_OPENDCL                     30
#define IDR_ODCDOCTEMPLATE              40
#define IDS_PROJECT                     53
#define IDS_MODALFORM                   54
#define IDS_MODELESSFORM                55
#define IDS_DOCKABLEFORM                56
#define IDS_CONFIGTAB                   57
#define IDS_TOOLBOX                     58
#define IDR_MAINFRAME                   59
#define IDR_ZTABORDER                   60
#define IDS_ZTABORDER                   61
#define IDS_TTTSENDTOBACK               62
#define IDS_TTTBRINGTOFRONT             63
#define IDS_TTTUPARROW                  64
#define IDS_TTTDOWNARROW                65
#define IDS_TTTHELP                     66
#define IDS_PROPERTIES                  67
#define IDS_EVENTS                      68
#define IDS_DEFFONT                     69
#define IDS_WINSYSCOLOR                 70
#define IDS_OTHERCOLORS                 71
#define IDS_PICTUREDESC                 72
#define IDS_RUNTIME                     73
#define IDS_METHOD                      75
#define IDS_PROPERTY                    76
#define IDS_DESCNOTSET                  77
#define IDS_EVENTTITLE                  78
#define IDS_FUNCADDED                   82
#define IDS_TAB                         83
#define IDS_UNTITILED                   84
#define IDS_DESIGNTIMEONLY              85
#define IDS_BADACTIVEX                  86
#define IDS_HIDDENPROP                  87
#define IDS_NOGRID                      88
#define IDS_AGRID                       89
#define IDS_WILLBE                      90
#define IDS_PASSWORD                    91
#define IDS_COPYTOCLIP                  92
#define IDS_COPYGETTOCLIP               93
#define IDS_RENAMEPROJECT               94
#define IDS_UPDATEVARNAMEQ              95
#define IDS_COMBODESC8                  97
#define IDS_COMBODESC9                  98
#define IDS_COMBODESC10                 99
#define IDS_SCROLLBARCOLOR              101
#define IDD_ABOUTBOX                    102
#define IDD_BLANKDIALOG                 103
#define IDD_FONTPAGE                    104
#define IDD_FORMVARNAMEUPDATE_DIALOG    105
#define IDD_TABPAGE_PROPERTIES          106
#define IDD_PICTUREFOLDER_DIALOG        107
#define IDD_OPENDCL_FORM                108
#define IDD_PROJECTPASSWORD             109
#define IDI_PASSWORD                    110
#define IDB_FILEDLGCTRL                 112
#define IDS_FILEDLG                     135
#define IDS_COPYTOCLIPBOARD             137
#define IDS_STRINGBOLD                  138
#define IDS_STRINGITALIC                139
#define IDD_GRIDSPACING_DIALOG          140
#define IDS_STRINGUL                    140
#define IDP_FAILED_TO_CREATE            141
#define IDS_COMBODESC11                 142
#define IDS_COMBODESC12                 143
#define IDS_PROPERTYTITLE               144
#define IDS_STRINGSCALED                145
#define IDS_ERRORONRET                  146
#define IDS_8F                          147
#define IDS_UNDERSCORE                  148
#define IDS_MICROSOFT                   149
#define IDD_INSERTCONTROL               152
#define IDD_COMPONENTCATEGORIES         156
#define IDS_AUTOLISPFILE                159
#define IDI_STDBUTTON                   164
#define IDI_GRAPHICBUTTON               165
#define IDI_FRAME                       166
#define IDI_CHECKBOX                    167
#define IDI_COMBOBOX                    168
#define IDI_TEXTBOX                     169
#define IDI_URL                         170
#define IDI_BLOCKLIST                   171
#define IDI_HTML                        178
#define IDS_SELECTTOIMPORT              180
#define IDI_LISTBOX                     181
#define IDI_LISTVIEW                    182
#define IDS_BOOL                        184
#define IDS_INT                         185
#define IDI_OPTION                      186
#define IDS_LONG                        186
#define IDS_REAL                        187
#define IDI_SCROLLBAR                   188
#define IDS_STRING                      188
#define IDI_PROGRESSBAR                 191
#define IDI_PICTUREBOX                  192
#define IDI_TABS                        193
#define IDS_OBJRETURNED                 193
#define IDI_TREE                        194
#define IDS_DllRegisterServer           194
#define IDS_DLL                         195
#define IDS_AXFILTER                    196
#define IDS_DclFormName                 197
#define IDS_MODALFORM2                  198
#define IDS_MODELESSFORM2               199
#define IDS_DOCKABLEFORM2               200
#define IDS_PROBLEMS                    201
#define IDS_OBJECTDCL                   202
#define IDS_CONFIGTAB2                  203
#define IDC_IMAGE                       204
#define IDS_DOT                         204
#define IDC_PREVIEW                     205
#define IDS_BOOLEAN                     205
#define IDR_TOOLBOX                     206
#define IDS_BACKGROUND                  206
#define IDS_FOREGROUND                  207
#define IDB_FILTER                      208
#define IDR_POPUPMENUS                  209
#define IDB_PICK                        210
#define IDS_ALREADYADDED                210
#define IDB_SELECT                      213
#define IDD_FILEOPENPREVIEW             213
#define IDC_SCALEDSTYLE                 214
#define IDC_PIXELSTYLE                  215
#define IDI_HELP                        216
#define IDC_HANDICON                    219
#define IDC_FILTER3                     219
#define IDC_FILTER2                     220
#define IDD_GEOMETRY                    221
#define IDC_FILTER0                     221
#define IDB_GEOMETRY                    222
#define IDC_COLOR                       222
#define IDC_BROWSE                      222
#define IDC_COPY2                       222
#define IDC_DROPLISTBTN                 222
#define IDC_CAPTION                     223
#define IDC_EDIT1                       223
#define IDC_COPY1                       223
#define IDC_TEXT                        223
#define IDC_BOLD                        224
#define IDC_CLEAR                       224
#define IDC_EDIT4                       224
#define IDC_COPY3                       224
#define IDC_ITALIC                      225
#define IDC_TTT                         225
#define IDC_EDIT5                       225
#define IDC_FILEEXT                     225
#define IDC_AVI                         226
#define IDC_EDIT6                       226
#define IDC_EVENTDESC                   226
#define IDD_COMBOBOX                    226
#define IDC_INDEX_EDIT                  226
#define IDC_EVENTSTREE                  227
#define IDD_EVENTS                      227
#define IDC_FILTER1                     228
#define IDD_EDITFILTERS                 228
#define IDC_PICLIST                     229
#define IDD_IMAGELIST                   229
#define IDI_MONTH                       229
#define IDD_BUTTONSTYLES                231
#define IDD_TABS                        232
#define IDC_EXAMPLEIMAGE                232
#define IDD_BACKCOLORS                  233
#define IDI_ANGLESLIDER                 233
#define IDC_SYSTEMCOLORLIST             234
#define IDC_EDIT                        235
#define IDI_SLIDERBAR                   235
#define IDC_COLORCOMBO                  237
#define IDI_ARROW                       237
#define IDC_DESCRIPTION                 238
#define IDI_COLOR                       238
#define IDI_LINEWEIGHT                  239
#define IDC_STYLE0                      240
#define IDI_3DRECT                      240
#define IDC_STYLE1                      241
#define IDI_SPINBUTTON                  241
#define IDC_STYLE2                      242
#define IDI_DWGPREVIEW                  242
#define IDC_STYLE3                      243
#define IDI_BLOCKVIEW                   243
#define IDC_STYLE4                      244
#define IDI_SLIDEVW                     244
#define IDC_STYLE5                      245
#define IDC_STYLE6                      246
#define IDC_COMBO0                      247
#define IDC_COMBO1                      248
#define IDI_ACTIVEX                     248
#define IDC_COMBOBOXEX                  249
#define IDD_PROPWIZARD                  250
#define IDC_DESC                        250
#define IDD_FORECOLORS                  251
#define IDC_FILTER4                     251
#define IDC_FILTER5                     252
#define IDD_WINCOLORDIALOG              253
#define IDC_FILTER6                     253
#define IDD_OBJECTBROWSER               254
#define IDC_FILTER7                     254
#define IDC_FILTER8                     255
#define IDI_CLOSEDFOLDER                255
#define IDC_FILTER                      256
#define IDI_DOCKABLE                    256
#define IDC_SELECT                      257
#define IDI_MODAL                       257
#define IDC_PICK                        258
#define IDI_LSP                         258
#define IDI_MODELESS                    259
#define IDC_ADDIMAGE                    260
#define IDI_OPENFOLDER                  260
#define IDC_REMOVEIMAGE                 261
#define IDC_EDITWIDTH                   262
#define IDI_TABFOLDER                   262
#define IDC_EDITHEIGHT                  263
#define IDI_ENUM                        263
#define IDI_EVENT                       264
#define IDI_METHOD                      265
#define IDI_PROPERTY                    266
#define IDI_ENUMS                       267
#define IDI_ACAD2002                    270
#define IDI_OPTIONLIST                  272
#define IDI_DWGLIST                     275
#define IDI_ANIMATE                     276
#define IDI_IMAGECOMBOBOX               277
#define IDI_AXFILE                      278
#define IDI_OLEOBJECT                   279
#define IDI_FILEDLG                     280
#define IDR_FONTBTNS                    285
#define IDD_SORTTABS                    300
#define IDD_COLUMNS                     301
#define IDI_GRID                        301
#define IDD_LISTCONTENTS                302
#define IDD_IMAGELISTCONTENTS           303
#define IDD_ALTCOLORS                   304
#define IDI_UNDERLINE                   304
#define IDD_TOOLTIPS                    305
#define IDI_BOLD                        305
#define IDI_ITALIC                      306
#define IDI_TEXTCOLOR                   307
#define IDI_WARN                        309
#define IDI_INFO                        310
#define IDI_SPLITTER                    312
#define IDD_HELPCTRLS                   315
#define IDI_HATCH                       315
#define IDD_PROGRESSBAR                 316
#define IDS_BUTTONSTYLE_0               501
#define IDS_BUTTONSTYLE_1               502
#define IDS_BUTTONSTYLE_2               503
#define IDS_BUTTONSTYLE_3               504
#define IDS_BUTTONSTYLE_4               505
#define IDS_BUTTONSTYLE_5               506
#define IDS_BUTTONSTYLE_6               507
#define IDS_COMBOBOXSTYLE_0             801
#define IDS_COMBOBOXSTYLE_1             802
#define IDS_COMBOBOXSTYLE_2             803
#define IDS_COMBOBOXSTYLE_3             804
#define IDS_COMBOBOXSTYLE_4             805
#define IDS_COMBOBOXSTYLE_5             806
#define IDS_COMBOBOXSTYLE_6             807
#define IDS_COMBOBOXSTYLE_7             808
#define IDS_COMBOBOXSTYLE_8             809
#define IDS_COMBOBOXSTYLE_9             810
#define IDS_COMBOBOXSTYLE_10            811
#define IDS_COMBOBOXSTYLE_11            812
#define IDS_COMBOBOXSTYLE_12            813
#define IDS_COMBOBOXSTYLE_13            814
#define IDS_PICTURESHORTCUT2            815
#define IDS_RUNTIMENOTALLOWEDCTRL       816
#define IDS_RUNTIMENOTALLOWEDDLG        817
#define IDS_PICTURESHORTCUT             818
#define IDS_NEWCOLUMNCAPTION            819
#define IDC_APPVERSION                  1001
#define IDC_LICENSETXT                  1002
#define IDC_PASSWORD                    1005
#define IDC_PICTURE                     1007
#define IDC_PICTURELIST                 1008
#define IDC_CTRL_DESC                   1009
#define IDC_PROPERTYTITLE               1012
#define IDC_ADDCANCEL                   1014
#define IDC_ADDTOLISP                   1015
#define IDC_DEFUNEDIT                   1016
#define IDC_DEFUNPREVIEW                1017
#define IDC_LABEL                       1018
#define IDC_TAB                         1019
#define IDC_LIST                        1020
#define IDC_RICHEDIT                    1024
#define IDC_SPIN                        1025
#define IDC_ADD                         1026
#define IDC_DELETE                      1027
#define IDC_FRAME                       1029
#define IDC_GRIDSLIDER                  1032
#define IDC_CURRENTSPACING              1033
#define IDC_OPTIONLIST                  1034
#define IDC_METHDEF                     1036
#define IDC_CTRLCHECK                   1036
#define IDC_PROPDESCEDIT                1037
#define IDC_STRIKEOUT                   0x0410
#define IDC_UNDERLINE                   0x0411
#define IDC_COLOR2                      1043
#define IDC_INSERT                      1048
#define IDC_SELECTALL                   1051
#define IDC_CONTROLS                    1053
#define IDC_INDEX                       1058
#define IDC_ALIGNMENT                   1060
#define IDC_CATEGORIES                  1064
#define IDC_STYLETITLE                  1064
#define IDC_DEFAULT                     1066
#define IDC_ALTERNATE                   1068
#define grp1                            0x0430
#define grp2                            0x0431
#define IDC_DEFICONLABEL                1073
#define IDC_ALTICONLABEL                1074
#define IDC_DATE                        1075
#define IDC_TIME                        1076
#define IDC_THELIST                     1076
#define IDC_COMBOBOXEX2                 1078
#define IDC_TRUEBTN                     1081
#define IDC_TITLE                       1082
#define IDC_LINE                        1083
#define IDC_SERVERPATH                  1083
#define IDC_AVILABEL                    1084
#define IDC_MAINTEXT                    1085
#define IDC_BALLOON                     1086
#define IDC_LEFT                        1087
#define IDC_TOP                         1088
#define stc1                            0x0440
#define IDC_BOTTOM                      1089
#define stc2                            0x0441
#define IDC_RIGHT                       1090
#define stc3                            0x0442
#define IDC_SAMPLE                      0x0444
#define IDC_RICHEDIT1                   1093
#define IDC_COLORPATCH                  1095
#define IDC_PERCENTAGE                  1096
#define IDC_PROGRESS1                   1097
#define IDC_STATIC1                     1098
#define IDC_STATIC2                     1099
#define IDC_STATIC3                     1100
#define IDC_STATIC4                     1101
#define IDC_STATIC5                     1102
#define IDC_FONT                        0x0470
#define IDC_STYLE                       0x0471
#define IDC_FONTSIZE                    0x0472
#define IDC_DISABLED                    1138
#define IDS_ARGS_ROWCOL                 1187
#define IDS_ARGS_ITEM                   1193
#define IDS_ARGS_KEY                    1194
#define IDS_ARGS_RECT                   1331
#define IDS_FILTERSTYLE_0               1701
#define IDS_FILTERSTYLE_1               1702
#define IDS_FILTERSTYLE_2               1703
#define IDS_FILTERSTYLE_3               1704
#define IDS_FILTERSTYLE_4               1705
#define IDS_FILTERSTYLE_5               1706
#define IDS_FILTERSTYLE_6               1707
#define IDS_FILTERSTYLE_7               1708
#define IDS_FILTERSTYLE_8               1709
#define IDS_FILETYPE                    1710
#define IDS_ObjectBrowser               2319
#define IDS_DRAGSTYLE                   2322
#define IDS_ROWHEADER                   2323
#define IDS_ALTROWCOLORDESC             2333
#define IDS_ALTROWCOLORDESC2            2334
#define IDS_ALTROWCOLORDESC3            2335
#define IDS_ALTROWCOLORDESC4            2336
#define IDS_ALTROWCOLORDESC5            2337
#define IDS_ALTROWCOLORDESC6            2338
#define IDS_ALTROWCOLORDESC7            2339
#define IDS_ALTROWCOLORDESC8            2340
#define IDS_ALTROWCOLORDESC9            2341
#define IDS_ALTROWCOLORDESC10           2342
#define IDS_ALTROWCOLORDESC11           2343
#define IDS_PROP_TITLEBAR_DESC          2352
#define IDS_PROP_TOOLTIPBALLOON_DESC    2354
#define IDS_ORIENTATION_0               2601
#define IDS_ORIENTATION_1               2602
#define IDS_SPLITTERStyle_0             2603
#define IDS_SPLITTERStyle_1             2604
#define IDS_SPLITTERStyle_2             2605
#define IDS_SPLITTERStyle_3             2606
#define IDS_SPLITTERStyle_4             2607
#define IDS_RECTSTYLE_0                 2801
#define IDS_RECTSTYLE_1                 2802
#define IDS_RECTSTYLE_2                 2803
#define IDS_RECTSTYLE_3                 2804
#define IDS_RECTSTYLE_4                 2805
#define IDS_COMBODESC0                  2810
#define IDS_COMBODESC1                  2811
#define IDS_COMBODESC2                  2812
#define IDS_COMBODESC3                  2813
#define IDS_COMBODESC4                  2814
#define IDS_COMBODESC5                  2815
#define IDS_COMBODESC6                  2816
#define IDS_COMBODESC7                  2817
#define IDS_TEXTBOXFILTER0              2825
#define IDS_TEXTBOXFILTER1              2826
#define IDS_TEXTBOXFILTER2              2827
#define IDS_TEXTBOXFILTER3              2828
#define IDS_TEXTBOXFILTER4              2829
#define IDS_TEXTBOXFILTER5              2830
#define IDS_TEXTBOXFILTER6              2831
#define IDS_TEXTBOXFILTER7              2832
#define IDS_TEXTBOXFILTER8              2833
#define IDS_BUTTONSTYLE0                2840
#define IDS_BUTTONSTYLE1                2841
#define IDS_BUTTONSTYLE2                2842
#define IDS_BUTTONSTYLE3                2843
#define IDS_BUTTONSTYLE4                2844
#define IDS_BUTTONSTYLE5                2845
#define IDS_BUTTONSTYLE6                2846
#define IDS_OPENPROJECTFILE             3000
#define IDS_JUSTIFICATION_0             4301
#define IDS_JUSTIFICATION_1             4302
#define IDS_JUSTIFICATION_2             4303
#define IDS_EVENTDESC_BTNCLICKED        5000
#define IDS_EVENTDESC_RCLICK            5009
#define IDS_EVENTDESC_RDBLCLICK         5010
#define IDS_SELECTSTYLE_0               5101
#define IDS_SELECTSTYLE_1               5102
#define IDS_SELECTSTYLE_2               5103
#define IDS_EVENTDESC_SPLITTERMOVED     5224
#define IDS_TAB_JUSTIFY_0               6201
#define IDS_TAB_JUSTIFY_1               6202
#define IDS_TABSTYLE_0                  6301
#define IDS_TABSTYLE_1                  6302
#define IDS_TABALIGN_0                  6401
#define IDS_TABALIGN_1                  6402
#define IDS_URL_TYPE_0                  6601
#define IDS_URL_TYPE_1                  6602
#define IDS_ONEVENT_0                   8301
#define IDS_ONEVENT_1                   8302
#define IDS_ONEVENT_2                   8303
#define IDS_BV_UM_0                     11701
#define IDS_BV_UM_1                     11702
#define IDS_BV_UM_2                     11703
#define IDS_BV_UM_3                     11704
#define IDS_ADDTOSTRING                 12514
#define IDI_X                           12515
#define ID_EDIT_DELETE                  12771
#define ID_BRINGTOFRONT                 12772
#define ID_SENDTOBACK                   12773
#define ID_PROPERTIES                   12774
#define ID_ADDMODAL                     12775
#define ID_ADDMODELESS                  12776
#define ID_ADDDOCKABLE                  12777
#define ID_ADDCONFIG                    12778
#define ID_PICTUREFOLDER                12779
#define ID_SETAUTOLISPFILENAME          12780
#define ID_REMOVE                       12781
#define ID_TOOLS_OPTIONS                12782
#define ID_TOOLS_IMAGEEDITOR            12783
#define ID_LC_TRANSFER                  12784
#define IDS_ZMOVEUP                     12785
#define IDS_ZMOVEDOWN                   12786
#define IDS_ZHELP                       12787
#define IDS_DCLTREEITEMNOTSEL           12788
#define IDS_QDELETEFORM                 12789
#define IDS_QDELETEFORMWTAB             12790
#define IDS_CTRLBADNAME                 12791
#define IDS_FORMBADNAME                 12792
#define IDS_TABNO                       12793
#define IDS_NOMORETABS                  12794
#define IDS_NOTABWITHINTAB              12795
#define IDS_QDELETETAB                  12796
#define IDS_AXFILEPARENT                12797
#define IDS_INDEX                       12798
#define IDS_NEWITEM                     12799
#define IDS_CTRLHELP                    12800
#define ID_FILE_REGISTERCONTROLS        12806
#define ID_TOOLBOX_POINTER              12816
#define ID_TOOLBOX_LABEL                12817
#define ID_TOOLBOX_TEXTBUTTON           12818
#define ID_TOOLBOX_GRAPHICBUTTON        12819
#define ID_TOOLBOX_FRAME                12820
#define ID_TOOLBOX_TEXTBOX              12821
#define ID_TOOLBOX_CHECKBOX             12822
#define ID_TOOLBOX_OPTION               12823
#define ID_TOOLBOX_COMBOBOX             12824
#define ID_TOOLBOX_LISTBOX              12825
#define ID_TOOLBOX_SCROLLBAR            12826
#define ID_TOOLBOX_SLIDER               12827
#define ID_TOOLBOX_PICTUREBOX           12828
#define ID_TOOLBOX_TABS                 12829
#define ID_TOOLBOX_MONTHPICKER          12830
#define ID_TOOLBOX_TREE                 12831
#define ID_TOOLBOX_RECTANGLE            12832
#define ID_TOOLBOX_PROGRESSBAR          12833
#define ID_TOOLBOX_SPINBUTTON           12834
#define ID_TOOLBOX_URLLINK              12835
#define ID_TOOLBOX_ANGLESLIDER          12836
#define ID_TOOLBOX_BLOCKVIEW            12837
#define ID_TOOLBOX_SLIDEVIEW            12838
#define ID_TOOLBOX_HTML                 12839
#define ID_TOOLBOX_DWGPREVIEW           12840
#define ID_TOOLBOX_LISTVIEW             12841
#define ID_TOOLBOX_BLOCKLIST            12842
#define ID_TOOLBOX_OPTIONLIST           12843
#define ID_TOOLBOX_ACTIVEX              12844
#define ID_TOOLBOX_DWGLIST              12845
#define ID_TOOLBOX_ANIMATE              12846
#define ID_TOOLBOX_IMAGECOMBOBOX        12847
#define ID_TOOLBOX_GRID                 12848
#define ID_TOOLBOX_SPLITTER             12849
#define ID_TOOLBOX_HATCH                12850
#define ID_TOOLS_DEFAULTFONT            12870
#define ID_MOVEZFRONTBY1                12874
#define ID_MOVEZBACKBY1                 12875
#define ID_ZORDERHELP                   12876
#define ID_DOCK_TOOLBOX                 12879
#define ID_DOCK_ZORDER                  12880
#define ID_DOCK_PROJECT                 12881
#define ID_DOCK_PROPERTIES              12882
#define ID_TOOLS_GRIDSPACING            12893
#define ID_SETDISTFILENAME              12894
#define ID_WINDOW_CLOSEALL              12896
#define ID_EDIT_OBJECTBROWSER           12897
#define ID_PROJECTS_ADDFILEDIALOGBOX    12898
#define ID_TOOLS_EVENTSCOPYTOCLIPBOARD  12901
#define ID_TOOLS_EVENTSWRITETOLISPFILE  12902
#define ID_FONTBOLDBTN                  12903
#define ID_FONTITALICBTN                12904
#define ID_FONTUNDERLINEBTN             12905
#define ID_FONTSCALED                   12907
#define ID_EDIT_PROPERTIES              12916
#define ID_BUTTON12869                  12927
#define ID_BUTTON12932                  12932
#define ID_TOOLBOX_IMAGELIST            12933
#define ID_BUTTON12937                  12937
#define ID_BUTTON12939                  12939
#define IDS_CAPTIONOPTIONS              14191
#define IDS_APROPNAME_USERMODE          14449
#define IDS_APROPNAME_UIDEAD            14450
#define IDS_APROPNAME_SHOWHATCHING      14451
#define IDS_APROPNAME_SHOWGRABHANDLES   14452
#define IDS_APROPNAME_TEXTALIGN         14453
#define IDS_APROPNAME_BACKCOLOR         14454
#define IDS_APROPNAME_FORECOLOR         14455
#define IDS_APROPNAME_FONT              14456
#define IDS_APROPNAME_SCALEUNITS        14458
#define IDS_APROPNAME_MESSAGEREFLECT    14459
#define IDS_APROPNAME_LOCALEID          14460
#define IDS_APROPNAME_SUPPORTSMNEMONICS 14461
#define IDS_UNREGISTERSERVERFAILED      14462
#define IDS_PROGID                      14479
#define IDS_PATH                        14480
#define IDS_PROPERTYEDITREQUESTFORMAT   14484
#define IDS_IMPLEMENTEDCATEGORIES       14490
#define IDS_REQUIREDCATEGORIES          14491
#define IDS_CREATEFAILED                14494
#define IDS_COPYFAILED                  14510
#define IDS_SERVERNOTFOUND              14514
#define IDS_PROJECTFILENAME             14552
#define IDS_PROJECTNAME                 14553
#define IDS_AS                          14554
#define IDS_OPTIONAL                    14563
#define IDS_OLENOTE1                    14568
#define IDS_OLENOTE2                    14569
#define IDS_FORMOREINFO                 14586
#define IDS_TOFINDIT                    14587
#define IDS_OPTIONALNIL                 14593
#define IDS_ISA                         14602
#define IDS_ALISPSYN                    14603
#define IDS_ALSPS                       14604
#define IDS_ALGPS                       14605
#define IDS_OPTIONALNILASB              14622
#define IDS_GETPROP                     14625
#define IDS_NEWVAL                      14626
#define IDS_NEWVAL2                     14627
#define IDS_WHENFIN2                    14628
#define IDS_WHENFIN                     14629
#define IDS_WHENFIN3                    14630
#define IDS_PICDESC                     14633
#define IDS_SETPROP4                    14635
#define IDS_SETCOLORDESC                14636
#define IDS_REDCOLORDESC                14637
#define IDS_REDCOLORDESC2               14638
#define IDS_NEWVAL3                     14639
#define IDS_PICNOTVALID                 14641
#define IDS_LONGFILTER                  14642
#define IDS_DOUBLEFILTER                14643
#define IDS_ANYFILTER                   14644
#define IDS_DATEFILTER                  14645
#define IDS_UINTFILTER                  14646
#define IDS_VARIES                      14647
#define IDS_ACTCAPTION                  14648
#define IDS_INACTCAPT                   14649
#define IDS_MENU                        14650
#define IDS_WINDOW                      14651
#define IDS_WINFRAME                    14652
#define IDS_MENUTEXT                    14653
#define IDS_WINTEXT                     14654
#define IDS_CAPTEXT                     14655
#define IDS_ACTBORDER                   14656
#define IDS_INACTBORDER                 14657
#define IDS_APPWORK                     14658
#define IDS_Highlight                   14659
#define IDS_HighlightText               14660
#define IDS_BTNFACE                     14661
#define IDS_BTNSHDOW                    14662
#define IDS_GREYTEXT                    14663
#define IDS_BTNTEXT                     14664
#define IDS_INACTCAPTEXT                14665
#define IDS_BTNHLIGHT                   14666
#define IDS_PerD                        14667
#define IDS_REGULAR                     14668
#define IDS_BOLDITAL                    14669
#define IDS_ITALIC                      14670
#define IDS_OLENOTE3                    14671
#define IDS_BOLD                        14672
#define IDS_MSSERIF                     14673
#define IDS_SYSTEM                      14674
#define IDS_TERMINAL                    14675
#define IDS_SMFONTS                     14676
#define IDS_FIXEDSYS                    14677
#define IDS_COURIER                     14678
#define IDS_WEIRDDOTDOT                 14679
#define IDS_COL1                        14681
#define IDS_COL2                        14682
#define IDS_APROPNAME_DISPLAYNAME       14684
#define IDS_PROPERTYVALUE               14685
#define IDS_BV_RM_0                     15401
#define IDS_BV_RM_1                     15402
#define IDS_BV_RM_2                     15403
#define IDS_BV_RM_3                     15404
#define IDS_BV_RM_4                     15405
#define IDS_BV_RM_5                     15406
#define IDS_BV_RM_6                     15407
#define IDS_BV_RM_7                     15408
#define IDS_LV_STYLE_0                  16101
#define IDS_LV_STYLE_1                  16102
#define IDS_LV_STYLE_2                  16103
#define IDS_LV_STYLE_3                  16104
#define IDS_LV_STYLE_4                  16105
#define IDS_LV_SORT_0                   16201
#define IDS_LV_SORT_1                   16202
#define IDS_LV_SORT_2                   16203
#define IDS_LV_IA_0                     16301
#define IDS_LV_IA_1                     16302
#define IDS_BL_STYLE_0                  16401
#define IDS_BL_STYLE_1                  16402
#define IDS_DEFICON                     17347
#define IDS_DATEFORMAT                  17348
#define IDS_TIMEFORMAT                  17349
#define IDS_CANNOTREMOVETABPANE         17638
#define IDS_ALTCOLORS                   17671
#define IDS_DOC_SIDES_0                 18901
#define IDS_DOC_SIDES_1                 18902
#define IDS_DOC_SIDES_2                 18903
#define IDS_DOC_SIDES_3                 18904
#define IDS_DOC_SIDES_4                 18905
#define IDS_DOC_SIDES_5                 18906
#define IDS_DOC_DEFAULT_0               19001
#define IDS_DOC_DEFAULT_1               19002
#define IDS_DOC_DEFAULT_2               19003
#define IDS_DOC_DEFAULT_3               19004
#define IDS_EVENTINVOKE_0               19401
#define IDS_EVENTINVOKE_1               19402
#define IDS_DRAGSTYLE_0                 19601
#define IDS_DRAGSTYLE_1                 19602
#define IDS_FILEDLGSTYLE_0              20201
#define IDS_FILEDLGSTYLE_1              20202
#define ID_TOOLBOX_ANIMATION            40002
#define ID_TOOLS_SETLISPSYMBOLNAMES     40003
#define ID_TOOLS_CLEARLISPSYMBOLNAMES   40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40008
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
