#pragma once


// To add a new property, take the following steps:
//
// 1) Add a new property ID to the Id enumeration in this file (PropertyIds.h). Make sure you
//    update the _MaxId property id value so it is equal to the value of the highest property id
// 2) Define an API name for the new property by adding it at the bottom of PropertyNames.cpp
// 3) Add a localizable string resource for the property display name to all shared local language
//    resource files (SharedRes.*.rc). The resource ID must be [3200 + property id].
// 4) Add a localizable string resource for the property description to all studio local language
//    resource files (Studio.*.rc). The resource ID must be [55000 + property id].
// 5) If the property is not hidden, edit GetEditControlCreator() in PropertyGridCtrl.cpp
//    to return a function that creates an appropriate edit control for the property.
// 6) If the new property is an enumeration value, add resource strings for the display name of
//    each possible value to each local language resource file (SharedRes.*.rc), then add an
//    entry in PropEnumNames.cpp for defining the list of enumeration names.
// 7) If the new property is an event, add it to the list of events in the
//    CEventsTabPane::UpdateEvents() function (in EventsTabPane.cpp) and to the LoadArgsNDesc()
//    function (in LoadArgs.cpp).
// 8) Edit DclControlProp.cpp and add the property to any controls that support it.
// 9) Edit the relevant controls' OnApplyProperty() function to apply the value of the new
//    property to an instance of the control.


namespace Prop
{

enum Id
{
	_All = -2,
	_Private = -1,
	Name = 1,
	Custom = 2,
	AutoSize = 3,
	BorderStyle = 4,
	ButtonStyle = 5,
	Caption = 6,
	Cancel = 7, //unused
	ComboBoxStyle = 8,
	Default = 9, //unused
	Enabled = 10,
	EventBtnClicked = 11,
	EventClicked = 12,
	EventDblClicked = 13,
	EventEditChanged = 14,
	EventNodeClicked = 15, //unused
	EventSelChanged = 16,
	FilterStyle = 17,
	Height = 18,
	ImageList = 19,
	LargeChange = 20,
	Left = 21,
	List = 22,
	MaxValue = 23,
	MinValue = 24,
	MultiRow = 25,
	Orientation = 26,
	Picture = 27,
	RectStyle = 28,
	SmallChange = 29,
	TabsCaption = 30,
	TabsImageList = 31,
	TabsTTT = 32,
	Text = 33,
	TickFrequency = 34,
	TitleBarText = 35,
	ToolTipTitle = 36,
	Top = 37,
	Value = 38,
	Visible = 39,
	Width = 40,
	ShowTicks = 41,
	ReadOnly = 42,
	Justification = 43,
	MarginLeft = 44,
	MarginRight = 45,
	LimitText = 46,
	AutoHScroll = 47,
	AutoVScroll = 48,
	DropDownHeight = 49,
	MultiColumn = 50,
	SelectionStyle = 51, //unused
	NoIntegralHeight = 52,
	Sorted = 53,
	UseTabStops = 54,
	DisableNoScroll = 55,
	HScrollBar = 56,
	VScrollBar = 57,
	ColumnWidth = 58,
	SmoothProgress = 59,
	AutoWrap = 60,
	URLAddress = 61,
	TabJustification = 62,
	TabStyle = 63,
	LabelAlignment = 64, //unused
	TabFixedWidth = 65,
	URLLinkType = 66,
	MinTabWidth = 67,
	TabSelected = 68,
	ItemData = 69,
	BtnCaption = 70,
	ToolBarBtnImages = 71, //unused
	BtnTTText = 72,
	ToolBarBtnStyle = 73, //unused
	UseTopFromBottom = 74,
	UseBottomFromBottom = 75,
	UseLeftFromRight = 76,
	UseRightFromRight = 77,
	TopFromBottom = 78,
	BottomFromBottom = 79,
	LeftFromRight = 80,
	RightFromRight = 81,
	Resizable = 82,
	OnEvent = 83, //unused
	MultiSelection = 84,
	EventGetDayState = 85,
	EventSelect = 86,
	EventKillFocus = 87,
	EventOutOfMemory = 88,
	EventRClick = 89,
	EventRDblClick = 90,
	EventReturn = 91,
	EventSetFocus = 92,
	EventBeginLabelEdit = 93,
	EventDeleteItem = 94,
	EventEndLabelEdit = 95,
	EventItemExpanded = 96,
	EventItemExpanding = 97,
	EventKeyDown = 98,
	EventSelChanging = 99,
	EventChanged = 100,
	EventMaxText = 101,
	EventUpdate = 102,
	EventDropDown = 103,
	EventScroll = 104,
	EventReleasedCapture = 105,
	FontUnderline = 106,
	FontItalic = 107,
	FontBold = 108,
	FontSize = 109,
	FontName = 110,
	FontStrikeout = 111,
	FontColor = 112,
	BlockName = 113,
	FileName = 114, //unused
	Color = 115, //unused
	CfgTabCaption = 116,
	AllowOrbiting = 117,
	FormEventClose = 118,
	FormEventInitialize = 119,
	FormEventSize = 120,
	FormEventShow = 121,
	DocEventActivated = 122,
	CfgEventCancel = 123,
	CfgEventOK = 124,
	CfgEventHelp = 125,
	CfgEventApply = 126,
	BackgroundColor = 127,
	ShowSelectAlways = 128,
	Indent = 129,
	HasLines = 130,
	LinesAtRoot = 131,
	HasButtons = 132,
	EditLabels = 133,
	CheckBoxes = 134,
	Icon = 135,
	EventKeyUp = 136,
	EventMouseDown = 137,
	EventMouseUp = 138,
	EventMouseMove = 139,
	EventMouseMovedOff = 140,
	EventMouseDblClick = 141,
	EventMouseWheel = 142,
	EventPaint = 143,
	UseMask = 144,
	ShowEditBox = 145,
	EventNavigateComplete = 146,
	InputFilter = 147,
	TabOrder = 148,
	ShowOrbitCircles = 149,
	IsTabStop = 150,
	EventMouseEntered = 151,
	BeginGroup = 152,
	MouseOverPicture = 153,
	RenderMode = 154,
	EventReturnPressed = 155,
	FormEventCancelClose = 156,
	OnLMouseEvent = 157,
	OnMMouseEvent = 158,
	OnRMouseEvent = 159,
	ZOrder = 160, //unused
	ListViewStyle = 161,
	ListViewSort = 162,
	ListViewIconAlign = 163,
	BlockListStyle = 164,
	AutoArrange = 165,
	ColHeader = 166,
	LabelWrap = 167,
	AllowScrolling = 168, //unused
	MultiSelect = 169,
	IconXSpacing = 170,
	IconYSpacing = 171,
	DragnDropToAutoCAD = 172,
	DragnDropFromControl = 173,
	DragnDropFromAutoCAD = 174,
	DragnDropBegin = 175,
	DragnDropAllowBegin = 176,
	DragnDropAllowDrop = 177,
	GridLines = 178,
	FullRowSelect = 179,
	MinDialogWidth = 180,
	MaxDialogWidth = 181,
	MinDialogHeight = 182,
	MaxDialogHeight = 183,
	EventColumnClick = 184,
	FontSizeStyle = 185,
	ForegroundColor = 186,
	Transparent = 187, //unused
	EventScrolled = 188,
	DockableSides = 189,
	DefaultDockedSide = 190,
	EventInvoke = 194,
	ReturnAsTab = 195,
	SingleExpanded = 196,
	ActiveXPropPages = 197,
	RowHeight = 198,
	DefSelIndex = 199,
	ObjectBrowser = 200,
	GlobalVarName = 201,
	FileDlgStyle = 202,
	AsReadOnly = 203,
	CreationPrompt = 204,
	DefaultExtension = 205, //unused
	ExtCanBeDiff = 206,
	FileMustExist = 207,
	Filter = 208,
	OverWritePrompt = 209,
	PathMustExist = 210,
	ShowCancel = 211,
	ShowHelp = 212,
	ShowNameLabel = 213,
	ShowNameTextBox = 214,
	ShowOK = 215,
	ShowReadOnlyCheckBox = 216,
	ShowTypeComboBox = 217,
	ShowTypeLabel = 218,
	EventFolderChanged = 219,
	EventOnHelp = 220,
	EventOnTypeChange	= 221,
	InsertOrXref = 222,
	RowHeader = 223,
	ColumnCaptions = 224,
	ColumnAlignments = 225,
	ColumnImages = 226,
	ColumnWidths = 227,
	ColumnStyles = 228,
	ColumnDefaultImages = 229,
	ColumnAlternateImages = 230,
	ColumnListItems = 231,
	ColumnListImages = 232,
	AlternateColor = 233,
	AlternateOrient = 234,
	ToolTipBody = 235,
	ToolTipPicture = 236,
	ToolTipAviFileName = 237,
	ToolTipLine = 238,
	ToolTipTitleColor = 239,
	SplitterStyle = 240,
	SplitterMin = 241,
	SplitterMax = 242,
	HatchScale = 243,
	EventSplitterMoved = 244,
	SecondText = 245,
	SecondsText = 246,
	MinuteText = 247,
	MinutesText = 248,
	DisplaySeconds = 249, //deprecated
	DisplayPercentage = 250, //deprecated
	FormEventOnOk = 251,
	TitleBar = 252,
	FormEventOnCancel = 253,
	ToolTipBalloon = 254,
	DocEventEnteringNoDocState = 255,
	UseVisualStyle = 256,
	RemainingText = 257,
	ProgressLegend = 258,
	KeepFocus = 259,
	_MinId = 1,
	_MaxId = 259
};

}; //namespace Prop
