//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SharedRes.rc
//
#define IDS_NONE                        21
#define IDS_DEFAULTFONT                 26
#define IDR_MAINFRAME                   59
#define IDS_AXMETHODS                   74
#define IDB_FOLDER                      129
#define IDS_DefaultFontName             153
#define IDS_DefaultFontSize             154
#define IDS_DefaultFontItalic           155
#define IDS_DefaultFontUnderLine        156
#define IDS_DefaultFontBold             157
#define IDS_DefaultFontSizeStyle        158
#define IDS_DOTLSP                      160
#define IDS_COLOR                       163
#define IDS_OLEOBJECT                   164
#define IDS_THEFILE                     165
#define IDS_COULDNOTOPEN                166
#define IDS_ODCFILTER                   179
#define IDB_ARROWHEADS                  202
#define IDI_FOLDER                      208
#define IDS_PROP_NAME                   211
#define IDS_PROP_CUSTOM                 212
#define IDS_PROP_AUTOSIZE               213
#define IDS_PROP_BORDERSTYLE            214
#define IDS_PROP_BTNSTYLE               215
#define IDS_PROP_CAPTION                216
#define IDS_PROP_CANCEL                 217
#define IDS_PROP_COMBOBOXSTL            218
#define IDS_PROP_DEFAULT                219
#define IDS_PROP_ENABLE                 220
#define IDS_PROP_EVNTBTN                221
#define IDS_PROP_EVNTCLICKED            222
#define IDS_PROP_EVNTDBLCLICKED         223
#define IDS_PROP_EVNTEDITCHANGED        224
#define IDS_PROP_EVNTNODECLICKED        225
#define IDS_PROP_EVNTSELCHANGED         226
#define IDS_PROP_FILTERSTYLE            227
#define IDS_PROP_HEIGHT                 228
#define IDS_PROP_IMAGELIST              229
#define IDS_PROP_LARGECHNGE             230
#define IDS_PROP_LEFT                   231
#define IDS_PROP_LIST                   232
#define IDS_PROP_MAXVAL                 233
#define IDS_PROP_MINVAL                 234
#define IDS_PROP_MULTIROW               235
#define IDS_PROP_ORIENTATION            236
#define IDS_PROP_PICTURE                237
#define IDS_PROP_RECTSTYLE              238
#define IDS_PROP_SMALLCHNG              239
#define IDS_PROP_TABSCAPTION            240
#define IDS_PROP_TABSIMAGELIST          241
#define IDS_PROP_TABSTTTLIST            242
#define IDS_PROP_TEXT                   243
#define IDS_PROP_TICKFRQCY              244
#define IDS_PROP_TITLEBARTEXT           245
#define IDS_PROP_TTT                    246
#define IDS_PROP_TOP                    247
#define IDS_PROP_VALUE                  248
#define IDS_PROP_VISIBLE                249
#define IDS_PROP_WIDTH                  250
#define IDS_PROP_SHOWTICKS              251
#define IDS_PROP_READONLY               252
#define IDS_PROP_JUSTIFICATION          253
#define IDS_PROP_MARGINLEFT             254
#define IDS_PROP_MARGINRIGHT            255
#define IDS_PROP_LIMITTEXT              256
#define IDB_OPBTNSELH                   256
#define IDS_PROP_AUTOHSCROLL            257
#define IDB_OPBTNNON                    257
#define IDS_PROP_AUTOVSCROLL            258
#define IDB_OPBTNSEL                    258
#define IDS_PROP_DROPDOWNHEIGHT         259
#define IDB_OPBTNNONH                   259
#define IDS_PROP_MULTICOL               260
#define IDS_PROP_SELECTSTYLE            261
#define IDS_PROP_NOINTEGRALHEIGHT       262
#define IDS_PROP_SORTED                 263
#define IDS_PROP_USETABSTOPS            264
#define IDS_PROP_DISABLENOSCROLL        265
#define IDS_PROP_HSCROLL                266
#define IDS_PROP_VSCROLL                267
#define IDS_PROP_COLWIDTH               268
#define IDS_PROP_SMOOTHPROG             269
#define IDS_PROP_AUTOWRAP               270
#define IDS_PROP_URLADDRESS             271
#define IDS_PROP_TAB_JUSTIFIED          272
#define IDS_PROP_TAB_STYLE              273
#define IDS_PROP_TAB_LABEL_ALIGN        274
#define IDS_PROP_TAB_FIXEDWIDTH         275
#define IDS_PROP_URLLINKTYPE            276
#define IDS_PROP_MINTABWIDTH            277
#define IDS_PROP_TABSELECTED            278
#define IDS_PROP_ITEMDATA               279
#define IDS_PROP_TOOLBARBTN_CAPTIONS    280
#define IDS_PROP_TOOLBARBTN_IMAGES      281
#define IDS_PROP_TOOLBARBTN_TTTEXT      282
#define IDS_PROP_TOOLBARBTN_STYLES      283
#define IDS_PROP_USETOPFROMBOTTOM       284
#define IDS_PROP_USEBOTTOMFROMBOTTOM    285
#define IDS_PROP_USELEFTFROMRIGHT       286
#define IDS_PROP_USERIGHTFROMRIGHT      287
#define IDS_PROP_TOPFROMBOTTOM          288
#define IDS_PROP_BOTTOMFROMBOTTOM       289
#define IDS_PROP_LEFTFROMRIGHT          290
#define IDS_PROP_RIGHTFROMRIGHT         291
#define IDS_PROP_RESIZABLE              292
#define IDS_PROP_FORMCONTROLABILITY     293
#define IDS_PROP_MULTISELECT            294
#define IDS_PROP_EVENTGETDAYSTATE       295
#define IDS_PROP_EVENTSELECT            296
#define IDS_PROP_EVENTKILLFOCUS         297
#define IDS_PROP_EVENTOUTOFMEM          298
#define IDS_PROP_EVENTRCLICK            299
#define IDS_PROP_EVENTRDBLCLICK         300
#define IDS_PROP_EVENTRETURN            301
#define IDS_PROP_EVENTSETFOCUS          302
#define IDS_PROP_EVENTBGNLBLEDIT        303
#define IDS_PROP_EVENTDELETEITEM        304
#define IDS_PROP_EVENTEDITLABELITEM     305
#define IDS_PROP_EVENTITEMEXPANED       306
#define IDS_PROP_EVENTITEMEXPANDING     307
#define IDS_PROP_EVENTKEYDOWN           308
#define IDS_PROP_EVENTSELCHANGING       309
#define IDS_PROP_EVENTCHANGED           310
#define IDS_PROP_EVENTMAXTEXT           311
#define IDS_PROP_EVENTUPDATE            312
#define IDS_PROP_EVENTDROPDOWN          313
#define IDS_PROP_EVENTSCROLL            314
#define IDS_PROP_EVENTRELEASEDCAPTURE   315
#define IDS_PROP_LABEL_UNDERLINE        316
#define IDS_PROP_LABEL_ITALIC           317
#define IDS_PROP_LABEL_BOLD             318
#define IDS_PROP_LABEL_SIZE             319
#define IDS_PROP_LABEL_NAME             320
#define IDS_PROP_LABEL_FLASHTEXT        321
#define IDS_PROP_LABEL_ROTATIONANGLE    322
#define IDS_PROP_BLOCKNAME              323
#define IDS_PROP_FILENAME               324
#define IDS_PROP_COLOR                  325
#define IDS_PROP_CFGTABCAPTION          326
#define IDS_PROP_ALLOWORBIT             327
#define IDS_PROP_FORMEVENTCLOSE         328
#define IDS_PROP_FORMEVENTINIT          329
#define IDS_PROP_FORMEVENTSIZE          330
#define IDS_PROP_FORMEVENTSHOW          331
#define IDS_PROP_DOCEVENTACTIVATE       332
#define IDS_PROP_CNFEVENTCANCEL         333
#define IDS_PROP_CNFEVENTOK             334
#define IDS_PROP_CNFEVENTHELP           335
#define IDS_PROP_CNFEVENTAPPLY          336
#define IDS_PROP_ACADBKCOLOR            337
#define IDS_PROP_SHOWSELALWAYS          338
#define IDS_PROP_INDENT                 339
#define IDS_PROP_HASLINES               340
#define IDS_PROP_LINESATROOT            341
#define IDS_PROP_HASBUTTONS             342
#define IDS_PROP_EDITLABLE              343
#define IDS_PROP_HASCHECKBOXES          344
#define IDS_PROP_TITLEBARICON           345
#define IDS_PROP_EVENTKEYUP             346
#define IDI_ACADFONT                    347
#define IDS_PROP_EVENTMOUSEDOWN         347
#define IDI_TRUEFONT                    348
#define IDS_PROP_EVENTMOUSEUP           348
#define IDS_PROP_EVENTMOUSEMOVE         349
#define IDS_PROP_EVENTMOUSEMOVEDOFF     350
#define IDS_PROP_EVENTMOUSEDBLCLICK     351
#define IDS_PROP_EVENTMOUSEWHEEL        352
#define IDS_PROP_EVENTPAINT             353
#define IDS_PROP_USEMASK                354
#define IDS_PROP_SHOWEDITBOX            355
#define IDI_PICSM                       356
#define IDS_PROP_EVENTNAVCOMPLETE       356
#define IDS_PROP_INPUTFILTER            357
#define IDS_PROP_TABORDER               358
#define IDS_PROP_SHOWORBITCIRCLES       359
#define IDS_PROP_ISTABSTOP              360
#define IDS_PROP_EVENTMOUSEENTERED      361
#define IDS_PROP_GROUP                  362
#define IDS_PROP_MOUSEOVERPICT          363
#define IDS_PROP_RENDERMODE             364
#define IDS_PROP_EVENTRETURNPRESSED     365
#define IDS_PROP_FORMEVENTCANCELCLOSE   366
#define IDS_PROP_EVENTLMOUSE            367
#define IDS_PROP_EVENTMMOUSE            368
#define IDS_PROP_EVENTRMOUSE            369
#define IDS_PROP_ZORDER                 370
#define IDS_PROP_LISTVIEWSTYLE          371
#define IDS_PROP_LVSORT                 372
#define IDS_PROP_ICONALIGN              373
#define IDS_PROP_BLOCKLISTSTYLE         374
#define IDS_PROP_AUTOARRANGE            375
#define IDS_PROP_COLHEADER              376
#define IDS_PROP_LABELWRAP              377
#define IDS_PROP_ALLOWSCROLLING         378
#define IDS_PROP_MULTISELECTION         379
#define IDS_PROP_ICONXSPACING           380
#define IDS_PROP_ICONYSPACING           381
#define IDS_PROP_DRAGDROPTOACAD         382
#define IDS_PROP_DRAGDROPFROMCTRL       383
#define IDS_PROP_DRAGDROPFROMACAD       384
#define IDS_PROP_DRAGDROPBEGIN          385
#define IDS_PROP_DRAGNDROPALLOWBEGIN    386
#define IDS_PROP_DRAGNDROPALLOWDROP     387
#define IDS_PROP_GRIDLINES              388
#define IDS_PROP_FULLROWSELECT          389
#define IDS_PROP_MINDLGWIDTH            390
#define IDS_PROP_MAXDLGWIDTH            391
#define IDS_PROP_MINDLGHEIGHT           392
#define IDS_PROP_MAXDLGHEIGHT           393
#define IDS_PROP_EVENTCOLCLICK          394
#define IDS_PROP_FONTSIZESTYLE          395
#define IDS_PROP_FORECOLOR              396
#define IDS_PROP_TRANSPARENT            397
#define IDS_PROP_EVENTSCROLLED          398
#define IDS_PROP_DOCSIDES               399
#define IDS_PROP_DOCDEFAULT             400
#define IDS_PROP_EVENTINVOKE            404
#define IDS_PROP_RETURNASTAB            405
#define IDS_PROP_SINGLEEXPANED          406
#define IDS_PROP_ACTIVEXPROPPAGES       407
#define IDS_PROP_ROWHEIGHT              408
#define IDS_PROP_DEFSELINDEX            409
#define IDS_PROP_VARNAME                411
#define IDS_PROP_FileDlgStyl            412
#define IDS_PROP_AsReadOnly             413
#define IDS_PROP_CreationPrompt         414
#define IDS_PROP_DefaultExtension       415
#define IDS_PROP_ExtCanBeDiff           416
#define IDS_PROP_FileMustExist          417
#define IDS_PROP_Filter                 418
#define IDS_PROP_OverWritePrompt        419
#define IDS_PROP_PathMustExist          420
#define IDS_PROP_ShowCancel             421
#define IDS_PROP_ShowHelp               422
#define IDS_PROP_ShowNameLabel          423
#define IDS_PROP_ShowNameTextBox        424
#define IDS_PROP_ShowOK                 425
#define IDS_PROP_ShowReadOnlyCheckBox   426
#define IDS_PROP_ShowTypeComboBox       427
#define IDS_PROP_ShowTypeLabel          428
#define IDS_EVENT_FolderChange          429
#define IDS_EVENT_HELP                  430
#define IDS_EVENT_TypeChange            431
#define IDS_PROP_INSERTTYPE             432
#define IDS_PROP_ROWHEADER              433
#define IDS_PROP_COLUMN_CAPTIONS        434
#define IDS_PROP_COLUMN_ALIGNMENTS      435
#define IDS_PROP_COLUMN_IMAGES          436
#define IDS_PROP_COLUMN_WIDTHS          437
#define IDS_PROP_COLUMN_STYLES          438
#define IDS_PROP_COLUMN_DEFAULTIMAGES   439
#define IDS_PROP_COLUMN_ALTERNATEIMAGES 440
#define IDS_PROP_COLUMN_LISTITEMS       441
#define IDS_PROP_COLUMN_LISTIMAGES      442
#define IDS_PROP_ALTERNATECOLOR         443
#define IDS_PROP_ALTORIENTATION         444
#define IDS_PROP_TOOLTIP_MAINTEXT       445
#define IDS_PROP_TOOLTIP_PICTURE        446
#define IDS_PROP_TOOLTIP_AVIFILENAME    447
#define IDS_PROP_TOOLTIP_LINE           448
#define IDS_PROP_TOOLTIP_TITLECOLOR     449
#define IDS_PROP_SPLITTERSTYLE          450
#define IDS_PROP_CLOSESTINSIDE          451
#define IDS_PROP_CLOSESTOUTSIDE         452
#define IDS_PROP_HATCHSCALE             453
#define IDS_EVENT_SPLITTERMOVED         454
#define IDS_PROP_CAPTION_SECOND         455
#define IDS_PROP_CAPTION_SECONDS        456
#define IDS_PROP_CAPTION_MINUTE         457
#define IDS_PROP_CAPTION_MINUTES        458
#define IDS_PROP_DISPLAYSECONDS         459
#define IDS_PROP_DISPLAY_PERCENTAGE     460
#define IDS_EVENT_FORM_ONOK             461
#define IDS_PROP_TITLEBAR               462
#define IDS_EVENT_FORM_ONCANCEL         463
#define IDS_PROP_TOOLTIP_BALLOON        464
#define IDS_EVENT_ENTERINGNODOCSTATE    465
#define IDS_EVENT_FORM_ENTERINGNODOCSTATE 465
#define IDI_LABEL                       10000
#define IDS_THE                         10001
#define IDS_RESETPROP                   10002
#define IDS_NOTLICENCEDAX               10003
#define IDS_BORDERSTYLE_0               10004
#define IDC_CURSOR1                     10004
#define IDC_HAND                        10004
#define IDS_BORDERSTYLE_1               10005
#define IDS_BORDERSTYLE_2               10006
#define IDI_FILTER                      10007
#define IDS_TRUE                        10007
#define IDI_PICK                        10008
#define IDS_FALSE                       10008
#define IDI_SELECT                      10009
#define IDS_LIST                        10009
#define IDS_CUSTOM                      10010
#define IDS_IMAGELIST                   10011
#define IDS_OPTION1                     10015
#define IDS_OPTION2                     10016
#define IDS_OPTION3                     10017
#define IDS_FILEDLGFILTERDEF            10021
#define IDS_SELFOLDER                   10022
#define IDS_OPEN                        10023
#define IDS_DCLFORM                     10099
#define IDS_POINTER                     10100
#define IDS_LABEL                       10101
#define IDS_TEXTBUTTON                  10102
#define IDS_GRAPHICBUTTON               10103
#define IDS_FRAME                       10104
#define IDS_TEXTBOX                     10105
#define IDS_CHECKBOX                    10106
#define IDS_OPTION                      10107
#define IDS_COMBOBOX                    10108
#define IDS_LISTBOX                     10109
#define IDS_SCROLLBAR                   10110
#define IDS_SLIDERBAR                   10111
#define IDS_PICTUREBOX                  10112
#define IDS_TABS                        10113
#define IDS_MONTHCAL                    10114
#define IDS_TREE                        10115
#define IDS_RECT                        10116
#define IDS_PROGRESSBAR                 10117
#define IDS_SPINBUTTON                  10118
#define IDS_URL                         10119
#define IDS_ROUNDSLIDER                 10120
#define IDS_BLOCKVIEW                   10121
#define IDS_SLIDEVIEW                   10122
#define IDS_HTML                        10123
#define IDS_DWGPREVIEW                  10124
#define IDS_LISTVIEW                    10125
#define IDS_BLOCKLIST                   10126
#define IDS_OPTIONLIST                  10127
#define IDS_ACTIVEX                     10128
#define IDS_DWGLIST                     10129
#define IDS_ANIMATION                   10130
#define IDS_IMAGECOMBOBOX               10131
#define IDS_GRID                        10132
#define IDS_SPLITTER                    10133
#define IDS_HATCH                       10134
#define IDS_FILEDLGCTRL                 10135

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10005
#define _APS_NEXT_COMMAND_VALUE         10501
#define _APS_NEXT_CONTROL_VALUE         10004
#define _APS_NEXT_SYMED_VALUE           10004
#endif
#endif
