//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SharedRes.*.rc
//
#define IDR_MAINFRAME                   10
#define IDS_NONE                        30
#define IDS_COLOR                       33
#define IDS_ODCFILTER                   34
#define IDS_SECONDTEXT                  35
#define IDS_SECONDSTEXT                 36
#define IDS_MINUTETEXT                  37
#define IDS_MINUTESTEXT                 38
#define IDS_REMAININGTEXT               39
#define IDS_COLORDISPLAYTEXT            40
#define IDS_OPTION1                     42
#define IDS_OPTION2                     43
#define IDS_OPTION3                     44
#define IDS_FILEDLGFILTERDEF            45
#define IDS_SELFOLDER                   46
#define IDS_OPEN                        47
#define IDS_TRUE                        48
#define IDS_FALSE                       49
#define IDS_LISPTYPE_BOOLEAN            60
#define IDS_LISPTYPE_INTEGER            61
#define IDS_LISPTYPE_LONG               62
#define IDS_LISPTYPE_FLOAT              63
#define IDS_LISPTYPE_STRING             64
#define IDS_LISPTYPE_HANDLE             65
#define IDS_LISPTYPE_VARIANT            66
#define IDS_LISPTYPE_AXOBJECT           67
#define IDS_LISPTYPE_OLECOLOR           68
#define IDI_HELP                        1100
#define IDI_INFO                        1101
#define IDI_WARN                        1102
#define IDI_ERR                         1103
#define IDI_LABEL                       1104
#define IDI_FILTER                      1105
#define IDI_PICK                        1106
#define IDI_SELECT                      1107
#define IDI_FOLDER                      1108
#define IDI_SHXFONT                     1109
#define IDI_TTFONT                      1110
#define IDI_PICKSMALL                   1111
#define IDI_LARGEBLOCK                  1112
#define IDB_ARROWHEADS                  1200
#define IDB_OPTBTN                      1201
#define IDB_OPTBTNSEL                   1202
#define IDB_OPTBTNH                     1203
#define IDB_OPTBTNSELH                  1204
#define IDB_OPTBTND                     1205
#define IDB_OPTBTNSELD                  1206
#define IDB_FOLDER                      1207
#define IDC_HAND                        1300
#define IDS_PROP_NAME                   3201
#define IDS_PROP_CUSTOM                 3202
#define IDS_PROP_AUTOSIZE               3203
#define IDS_PROP_BORDERSTYLE            3204
#define IDS_PROP_BTNSTYLE               3205
#define IDS_PROP_CAPTION                3206
#define IDS_PROP_CANCEL                 3207
#define IDS_PROP_COMBOBOXSTL            3208
#define IDS_PROP_DEFAULT                3209
#define IDS_PROP_ENABLE                 3210
#define IDS_EVENT_BTNCLICKED            3211
#define IDS_EVENT_CLICKED               3212
#define IDS_EVENT_DBLCLICKED            3213
#define IDS_EVENT_EDITCHANGED           3214
#define IDS_EVENT_NODECLICKED           3215
#define IDS_EVENT_SELCHANGED            3216
#define IDS_PROP_FILTERSTYLE            3217
#define IDS_PROP_HEIGHT                 3218
#define IDS_PROP_IMAGELIST              3219
#define IDS_PROP_LARGECHNGE             3220
#define IDS_PROP_LEFT                   3221
#define IDS_PROP_LIST                   3222
#define IDS_PROP_MAXVAL                 3223
#define IDS_PROP_MINVAL                 3224
#define IDS_PROP_MULTIROW               3225
#define IDS_PROP_ORIENTATION            3226
#define IDS_PROP_PICTURE                3227
#define IDS_PROP_RECTSTYLE              3228
#define IDS_PROP_SMALLCHNG              3229
#define IDS_PROP_TABSCAPTION            3230
#define IDS_PROP_TABSIMAGELIST          3231
#define IDS_PROP_TABSTTTLIST            3232
#define IDS_PROP_TEXT                   3233
#define IDS_PROP_TICKFRQCY              3234
#define IDS_PROP_TITLEBARTEXT           3235
#define IDS_PROP_TTT                    3236
#define IDS_PROP_TOP                    3237
#define IDS_PROP_VALUE                  3238
#define IDS_PROP_VISIBLE                3239
#define IDS_PROP_WIDTH                  3240
#define IDS_PROP_SHOWTICKS              3241
#define IDS_PROP_READONLY               3242
#define IDS_PROP_JUSTIFICATION          3243
#define IDS_PROP_MARGINLEFT             3244
#define IDS_PROP_MARGINRIGHT            3245
#define IDS_PROP_TEXTLIMIT              3246
#define IDS_PROP_AUTOHSCROLL            3247
#define IDS_PROP_AUTOVSCROLL            3248
#define IDS_PROP_DROPDOWNHEIGHT         3249
#define IDS_PROP_MULTICOL               3250
#define IDS_PROP_SELECTSTYLE            3251
#define IDS_PROP_NOINTEGRALHEIGHT       3252
#define IDS_PROP_SORTED                 3253
#define IDS_PROP_USETABSTOPS            3254
#define IDS_PROP_DISABLENOSCROLL        3255
#define IDS_PROP_HSCROLL                3256
#define IDS_PROP_VSCROLL                3257
#define IDS_PROP_COLWIDTH               3258
#define IDS_PROP_SMOOTHPROG             3259
#define IDS_PROP_AUTOWRAP               3260
#define IDS_PROP_HYPERLINK              3261
#define IDS_PROP_TAB_JUSTIFIED          3262
#define IDS_PROP_TAB_STYLE              3263
#define IDS_PROP_TAB_LABEL_ALIGN        3264
#define IDS_PROP_TAB_FIXEDWIDTH         3265
#define IDS_PROP_URLLINKTYPE            3266
#define IDS_PROP_MINTABWIDTH            3267
#define IDS_PROP_TABSELECTED            3268
#define IDS_PROP_ITEMDATA               3269
#define IDS_PROP_BTN_CAPTIONS           3270
#define IDS_PROP_BTN_IMAGES             3271
#define IDS_PROP_BTN_TOOLTIPS           3272
#define IDS_PROP_BTN_STYLES             3273
#define IDS_PROP_USETOPFROMBOTTOM       3274
#define IDS_PROP_USEBOTTOMFROMBOTTOM    3275
#define IDS_PROP_USELEFTFROMRIGHT       3276
#define IDS_PROP_USERIGHTFROMRIGHT      3277
#define IDS_PROP_TOPFROMBOTTOM          3278
#define IDS_PROP_BOTTOMFROMBOTTOM       3279
#define IDS_PROP_LEFTFROMRIGHT          3280
#define IDS_PROP_RIGHTFROMRIGHT         3281
#define IDS_PROP_RESIZABLE              3282
#define IDS_PROP_FORMCONTROLABILITY     3283
#define IDS_PROP_MULTISELECT            3284
#define IDS_EVENT_GETDAYSTATE           3285
#define IDS_EVENT_SELECT                3286
#define IDS_EVENT_KILLFOCUS             3287
#define IDS_EVENT_OUTOFMEM              3288
#define IDS_EVENT_RCLICK                3289
#define IDS_EVENT_RDBLCLICK             3290
#define IDS_EVENT_RETURN                3291
#define IDS_EVENT_SETFOCUS              3292
#define IDS_EVENT_BGNLBLEDIT            3293
#define IDS_EVENT_DELETEITEM            3294
#define IDS_EVENT_EDITLABELITEM         3295
#define IDS_EVENT_ITEMEXPANED           3296
#define IDS_EVENT_ITEMEXPANDING         3297
#define IDS_EVENT_KEYDOWN               3298
#define IDS_EVENT_SELCHANGING           3299
#define IDS_EVENT_CHANGED               3300
#define IDS_EVENT_MAXTEXT               3301
#define IDS_EVENT_UPDATE                3302
#define IDS_EVENT_DROPDOWN              3303
#define IDS_EVENT_SCROLL                3304
#define IDS_EVENT_RELEASEDCAPTURE       3305
#define IDS_PROP_FONTUNDERLINE          3306
#define IDS_PROP_FONTITALIC             3307
#define IDS_PROP_FONTBOLD               3308
#define IDS_PROP_FONTSIZE               3309
#define IDS_PROP_FONTNAME               3310
#define IDS_PROP_FONTSTRIKEOUT          3311
#define IDS_PROP_FONTCOLOR              3312
#define IDS_PROP_BLOCKNAME              3313
#define IDS_PROP_FILENAME               3314
#define IDS_PROP_COLOR                  3315
#define IDS_PROP_CFGTABCAPTION          3316
#define IDS_PROP_INTERFACEMODE          3317
#define IDS_EVENT_FORMCLOSE             3318
#define IDS_EVENT_FORMINIT              3319
#define IDS_EVENT_FORMSIZE              3320
#define IDS_EVENT_FORMSHOW              3321
#define IDS_EVENT_DOCACTIVATE           3322
#define IDS_EVENT_CFGCANCEL             3323
#define IDS_EVENT_CFGOK                 3324
#define IDS_EVENT_CFGHELP               3325
#define IDS_EVENT_CFGAPPLY              3326
#define IDS_PROP_ACADBKCOLOR            3327
#define IDS_PROP_SHOWSELALWAYS          3328
#define IDS_PROP_INDENT                 3329
#define IDS_PROP_HASLINES               3330
#define IDS_PROP_LINESATROOT            3331
#define IDS_PROP_HASBUTTONS             3332
#define IDS_PROP_EDITLABELS             3333
#define IDS_PROP_HASCHECKBOXES          3334
#define IDS_PROP_TITLEBARICON           3335
#define IDS_EVENT_KEYUP                 3336
#define IDS_EVENT_MOUSEDOWN             3337
#define IDS_EVENT_MOUSEUP               3338
#define IDS_EVENT_MOUSEMOVE             3339
#define IDS_EVENT_MOUSEMOVEDOFF         3340
#define IDS_EVENT_MOUSEDBLCLICK         3341
#define IDS_EVENT_MOUSEWHEEL            3342
#define IDS_EVENT_PAINT                 3343
#define IDS_PROP_USEMASK                3344
#define IDS_PROP_SHOWEDITBOX            3345
#define IDS_EVENT_NAVCOMPLETE           3346
#define IDS_PROP_INPUTFILTER            3347
#define IDS_PROP_TABORDER               3348
#define IDS_PROP_SHOWORBITCIRCLES       3349
#define IDS_PROP_ISTABSTOP              3350
#define IDS_EVENT_MOUSEENTERED          3351
#define IDS_PROP_GROUP                  3352
#define IDS_PROP_MOUSEOVERPICT          3353
#define IDS_PROP_RENDERMODE             3354
#define IDS_EVENT_RETURNPRESSED         3355
#define IDS_EVENT_FORMCANCELCLOSE       3356
#define IDS_EVENT_LMOUSE                3357
#define IDS_EVENT_MMOUSE                3358
#define IDS_EVENT_RMOUSE                3359
#define IDS_PROP_ZORDER                 3360
#define IDS_PROP_LISTVIEWSTYLE          3361
#define IDS_PROP_LVSORT                 3362
#define IDS_PROP_ICONALIGN              3363
#define IDS_PROP_BLOCKLISTSTYLE         3364
#define IDS_PROP_AUTOARRANGE            3365
#define IDS_PROP_COLHEADER              3366
#define IDS_PROP_LABELWRAP              3367
#define IDS_PROP_ALLOWSCROLLING         3368
#define IDS_PROP_MULTISELECTION         3369
#define IDS_PROP_ICONXSPACING           3370
#define IDS_PROP_ICONYSPACING           3371
#define IDS_EVENT_DRAGDROPTOACAD        3372
#define IDS_EVENT_DRAGDROPFROMCTRL      3373
#define IDS_EVENT_DRAGDROPFROMOTHER     3374
#define IDS_EVENT_DRAGDROPBEGIN         3375
#define IDS_PROP_DRAGNDROPALLOWBEGIN    3376
#define IDS_PROP_DRAGNDROPALLOWDROP     3377
#define IDS_PROP_GRIDLINES              3378
#define IDS_PROP_FULLROWSELECT          3379
#define IDS_PROP_MINDLGWIDTH            3380
#define IDS_PROP_MAXDLGWIDTH            3381
#define IDS_PROP_MINDLGHEIGHT           3382
#define IDS_PROP_MAXDLGHEIGHT           3383
#define IDS_EVENT_COLCLICK              3384
#define IDS_PROP_FONTSIZESTYLE          3385
#define IDS_PROP_FORECOLOR              3386
#define IDS_PROP_TRANSPARENT            3387
#define IDS_EVENT_SCROLLED              3388
#define IDS_PROP_DOCSIDES               3389
#define IDS_PROP_DOCDEFAULT             3390
#define IDS_PROP_EVENTINVOKE            3394
#define IDS_PROP_RETURNASTAB            3395
#define IDS_PROP_SINGLECLICKEXPAND          3396
#define IDS_PROP_ACTIVEXPROPPAGES       3397
#define IDS_PROP_ROWHEIGHT              3398
#define IDS_PROP_CURSELINDEX            3399
#define IDS_PROP_CONTROLBROWSER         3400
#define IDS_PROP_VARNAME                3401
#define IDS_PROP_FILEDLGSTYLE           3402
#define IDS_PROP_ASREADONLY             3403
#define IDS_PROP_CREATIONPROMPT         3404
#define IDS_PROP_DEFAULTEXTENSION       3405
#define IDS_PROP_EXTCANBEDIFF           3406
#define IDS_PROP_FILEMUSTEXIST          3407
#define IDS_PROP_FILTER                 3408
#define IDS_PROP_OVERWRITEPROMPT        3409
#define IDS_PROP_PATHMUSTEXIST          3410
#define IDS_PROP_SHOWCANCEL             3411
#define IDS_PROP_SHOWHELP               3412
#define IDS_PROP_SHOWNAMELABEL          3413
#define IDS_PROP_SHOWNAMETEXTBOX        3414
#define IDS_PROP_SHOWOK                 3415
#define IDS_PROP_SHOWREADONLYCHECKBOX   3416
#define IDS_PROP_SHOWTYPECOMBOBOX       3417
#define IDS_PROP_SHOWTYPELABEL          3418
#define IDS_EVENT_FOLDERCHANGED         3419
#define IDS_EVENT_HELP                  3420
#define IDS_EVENT_TYPECHANGED           3421
#define IDS_PROP_INSERTTYPE             3422
#define IDS_PROP_ROWHEADER              3423
#define IDS_PROP_COLUMN_CAPTIONS        3424
#define IDS_PROP_COLUMN_ALIGNMENTS      3425
#define IDS_PROP_COLUMN_IMAGES          3426
#define IDS_PROP_COLUMN_WIDTHS          3427
#define IDS_PROP_COLUMN_STYLES          3428
#define IDS_PROP_COLUMN_DEFAULTIMAGES   3429
#define IDS_PROP_COLUMN_ALTERNATEIMAGES 3430
#define IDS_PROP_COLUMN_LISTITEMS       3431
#define IDS_PROP_COLUMN_LISTIMAGES      3432
#define IDS_PROP_ALTERNATINGCOLOR       3433
#define IDS_PROP_ALTORIENTATION         3434
#define IDS_PROP_TOOLTIP_MAINTEXT       3435
#define IDS_PROP_TOOLTIP_PICTURE        3436
#define IDS_PROP_TOOLTIP_AVIFILENAME    3437
#define IDS_PROP_TOOLTIP_LINE           3438
#define IDS_PROP_TOOLTIP_TITLECOLOR     3439
#define IDS_PROP_SPLITTERSTYLE          3440
#define IDS_PROP_CLOSESTINSIDE          3441
#define IDS_PROP_CLOSESTOUTSIDE         3442
#define IDS_PROP_HATCHSCALE             3443
#define IDS_EVENT_SPLITTERMOVED         3444
#define IDS_PROP_CAPTION_SECOND         3445
#define IDS_PROP_CAPTION_SECONDS        3446
#define IDS_PROP_CAPTION_MINUTE         3447
#define IDS_PROP_CAPTION_MINUTES        3448
#define IDS_PROP_DISPLAYSECONDS         3449
#define IDS_PROP_DISPLAY_PERCENTAGE     3450
#define IDS_EVENT_FORM_ONOK             3451
#define IDS_PROP_TITLEBAR               3452
#define IDS_EVENT_FORM_ONCANCEL         3453
#define IDS_PROP_TOOLTIP_BALLOON        3454
#define IDS_EVENT_FORM_ENTERINGNODOCSTATE 3455
#define IDS_PROP_USEVISUALSTYLE         3456
#define IDS_PROP_CAPTION_REMAINING      3457
#define IDS_PROP_PROGRESSLEGEND         3458
#define IDS_PROP_KEEPFOCUS              3459
#define IDS_PROP_LISTIMAGES             3460
#define IDS_EVENT_DRAGOVERFROMCONTROL   3461
