#pragma once

// Common new UxTheme constants that may not be defined in older headers

#if (_MSC_VER == 1400)
#include <tmschema.h>
#endif


//
//  AEROWIZARDSTYLE class parts and states 
//
#define VSCLASS_AEROWIZARDSTYLE	L"AEROWIZARDSTYLE"
#define VSCLASS_AEROWIZARD	L"AEROWIZARD"

#define AW_TITLEBAR 1
#define AW_HEADERAREA 2
#define AW_CONTENTAREA 3
#define AW_COMMANDAREA 4
#define AW_BUTTON 5

#define AEROWIZARDSTYLEPARTS AEROWIZARDPARTS;

#define AW_S_TITLEBAR_ACTIVE 1
#define AW_S_TITLEBAR_INACTIVE 2

#define AW_S_HEADERAREA_NOMARGIN 1

#define AW_S_CONTENTAREA_NOMARGIN 1


//
//  BUTTONSTYLE class parts and states 
//
#define VSCLASS_BUTTONSTYLE	L"BUTTONSTYLE"
#define VSCLASS_BUTTON	L"BUTTON"

#define BP_PUSHBUTTON 1
#define BP_RADIOBUTTON 2
#define BP_CHECKBOX 3
#define BP_GROUPBOX 4
#define BP_USERBUTTON 5
#define BP_COMMANDLINK 6
#define BP_COMMANDLINKGLYPH 7

#define BUTTONSTYLEPARTS BUTTONPARTS;

#define PBS_NORMAL 1
#define PBS_HOT 2
#define PBS_PRESSED 3
#define PBS_DISABLED 4
#define PBS_DEFAULTED 5
#define PBS_DEFAULTED_ANIMATING 6

#define RBS_UNCHECKEDNORMAL 1
#define RBS_UNCHECKEDHOT 2
#define RBS_UNCHECKEDPRESSED 3
#define RBS_UNCHECKEDDISABLED 4
#define RBS_CHECKEDNORMAL 5
#define RBS_CHECKEDHOT 6
#define RBS_CHECKEDPRESSED 7
#define RBS_CHECKEDDISABLED 8

#define CBS_UNCHECKEDNORMAL 1
#define CBS_UNCHECKEDHOT 2
#define CBS_UNCHECKEDPRESSED 3
#define CBS_UNCHECKEDDISABLED 4
#define CBS_CHECKEDNORMAL 5
#define CBS_CHECKEDHOT 6
#define CBS_CHECKEDPRESSED 7
#define CBS_CHECKEDDISABLED 8
#define CBS_MIXEDNORMAL 9
#define CBS_MIXEDHOT 10
#define CBS_MIXEDPRESSED 11
#define CBS_MIXEDDISABLED 12
#define CBS_IMPLICITNORMAL 13
#define CBS_IMPLICITHOT 14
#define CBS_IMPLICITPRESSED 15
#define CBS_IMPLICITDISABLED 16
#define CBS_EXCLUDEDNORMAL 17
#define CBS_EXCLUDEDHOT 18
#define CBS_EXCLUDEDPRESSED 19
#define CBS_EXCLUDEDDISABLED 20

#define GBS_NORMAL 1
#define GBS_DISABLED 2

#define CMDLS_NORMAL 1
#define CMDLS_HOT 2
#define CMDLS_PRESSED 3
#define CMDLS_DISABLED 4
#define CMDLS_DEFAULTED 5
#define CMDLS_DEFAULTED_ANIMATING 6

#define CMDLGS_NORMAL 1
#define CMDLGS_HOT 2
#define CMDLGS_PRESSED 3
#define CMDLGS_DISABLED 4
#define CMDLGS_DEFAULTED 5


//
//  COMBOBOXSTYLE class parts and states 
//
#define VSCLASS_COMBOBOXSTYLE	L"COMBOBOXSTYLE"
#define VSCLASS_COMBOBOX	L"COMBOBOX"

#define CP_DROPDOWNBUTTON 1
#define CP_BACKGROUND 2
#define CP_TRANSPARENTBACKGROUND 3
#define CP_BORDER 4
#define CP_READONLY 5
#define CP_DROPDOWNBUTTONRIGHT 6
#define CP_DROPDOWNBUTTONLEFT 7
#define CP_CUEBANNER 8

#define COMBOBOXSTYLEPARTS COMBOBOXPARTS;

#define CBXS_NORMAL 1
#define CBXS_HOT 2
#define CBXS_PRESSED 3
#define CBXS_DISABLED 4

#define CBXSR_NORMAL 1
#define CBXSR_HOT 2
#define CBXSR_PRESSED 3
#define CBXSR_DISABLED 4

#define CBXSL_NORMAL 1
#define CBXSL_HOT 2
#define CBXSL_PRESSED 3
#define CBXSL_DISABLED 4

#define CBTBS_NORMAL 1
#define CBTBS_HOT 2
#define CBTBS_DISABLED 3
#define CBTBS_FOCUSED 4

#define CBB_NORMAL 1
#define CBB_HOT 2
#define CBB_FOCUSED 3
#define CBB_DISABLED 4

#define CBRO_NORMAL 1
#define CBRO_HOT 2
#define CBRO_PRESSED 3
#define CBRO_DISABLED 4

#define CBCB_NORMAL 1
#define CBCB_HOT 2
#define CBCB_PRESSED 3
#define CBCB_DISABLED 4


//
//  COMMUNICATIONSSTYLE class parts and states 
//
#define VSCLASS_COMMUNICATIONSSTYLE	L"COMMUNICATIONSSTYLE"
#define VSCLASS_COMMUNICATIONS	L"COMMUNICATIONS"

#define CSST_TAB 1

#define COMMUNICATIONSSTYLEPARTS COMMUNICATIONSPARTS;

#define CSTB_NORMAL 1
#define CSTB_HOT 2
#define CSTB_SELECTED 3


//
//  CONTROLPANELSTYLE class parts and states 
//
#define VSCLASS_CONTROLPANELSTYLE	L"CONTROLPANELSTYLE"
#define VSCLASS_CONTROLPANEL	L"CONTROLPANEL"

#define CPANEL_NAVIGATIONPANE 1
#define CPANEL_CONTENTPANE 2
#define CPANEL_NAVIGATIONPANELABEL 3
#define CPANEL_CONTENTPANELABEL 4
#define CPANEL_TITLE 5
#define CPANEL_BODYTEXT 6
#define CPANEL_HELPLINK 7
#define CPANEL_TASKLINK 8
#define CPANEL_GROUPTEXT 9
#define CPANEL_CONTENTLINK 10
#define CPANEL_SECTIONTITLELINK 11
#define CPANEL_LARGECOMMANDAREA 12
#define CPANEL_SMALLCOMMANDAREA 13
#define CPANEL_BUTTON 14
#define CPANEL_MESSAGETEXT 15
#define CPANEL_NAVIGATIONPANELINE 16
#define CPANEL_CONTENTPANELINE 17
#define CPANEL_BANNERAREA 18
#define CPANEL_BODYTITLE 19

#define CONTROLPANELSTYLEPARTS CONTROLPANELPARTS;

#define CPHL_NORMAL 1
#define CPHL_HOT 2
#define CPHL_PRESSED 3
#define CPHL_DISABLED 4

#define CPTL_NORMAL 1
#define CPTL_HOT 2
#define CPTL_PRESSED 3
#define CPTL_DISABLED 4
#define CPTL_PAGE 5

#define CPCL_NORMAL 1
#define CPCL_HOT 2
#define CPCL_PRESSED 3
#define CPCL_DISABLED 4

#define CPSTL_NORMAL 1
#define CPSTL_HOT 2


//
//  DATEPICKERSTYLE class parts and states 
//
#define VSCLASS_DATEPICKERSTYLE	L"DATEPICKERSTYLE"
#define VSCLASS_DATEPICKER	L"DATEPICKER"

#define DP_DATETEXT 1
#define DP_DATEBORDER 2
#define DP_SHOWCALENDARBUTTONRIGHT 3

#define DATEPICKERSTYLEPARTS DATEPICKERPARTS;

#define DPDT_NORMAL 1
#define DPDT_DISABLED 2
#define DPDT_SELECTED 3

#define DPDB_NORMAL 1
#define DPDB_HOT 2
#define DPDB_FOCUSED 3
#define DPDB_DISABLED 4

#define DPSCBR_NORMAL 1
#define DPSCBR_HOT 2
#define DPSCBR_PRESSED 3
#define DPSCBR_DISABLED 4


//
//  DRAGDROPSTYLE class parts and states 
//
#define VSCLASS_DRAGDROPSTYLE	L"DRAGDROPSTYLE"
#define VSCLASS_DRAGDROP	L"DRAGDROP"

#define DD_COPY 1
#define DD_MOVE 2
#define DD_UPDATEMETADATA 3
#define DD_CREATELINK 4
#define DD_WARNING 5
#define DD_NONE 6
#define DD_IMAGEBG 7
#define DD_TEXTBG 8

#define DRAGDROPSTYLEPARTS DRAGDROPPARTS;

#define DDCOPY_HIGHLIGHT 1
#define DDCOPY_NOHIGHLIGHT 2

#define DDMOVE_HIGHLIGHT 1
#define DDMOVE_NOHIGHLIGHT 2

#define DDUPDATEMETADATA_HIGHLIGHT 1
#define DDUPDATEMETADATA_NOHIGHLIGHT 2

#define DDCREATELINK_HIGHLIGHT 1
#define DDCREATELINK_NOHIGHLIGHT 2

#define DDWARNING_HIGHLIGHT 1
#define DDWARNING_NOHIGHLIGHT 2

#define DDNONE_HIGHLIGHT 1
#define DDNONE_NOHIGHLIGHT 2


//
//  EDITSTYLE class parts and states 
//
#define VSCLASS_EDITSTYLE	L"EDITSTYLE"
#define VSCLASS_EDIT	L"EDIT"

#define EP_EDITTEXT 1
#define EP_CARET 2
#define EP_BACKGROUND 3
#define EP_PASSWORD 4
#define EP_BACKGROUNDWITHBORDER 5
#define EP_EDITBORDER_NOSCROLL 6
#define EP_EDITBORDER_HSCROLL 7
#define EP_EDITBORDER_VSCROLL 8
#define EP_EDITBORDER_HVSCROLL 9

#define EDITSTYLEPARTS EDITPARTS;

#define ETS_NORMAL 1
#define ETS_HOT 2
#define ETS_SELECTED 3
#define ETS_DISABLED 4
#define ETS_FOCUSED 5
#define ETS_READONLY 6
#define ETS_ASSIST 7
#define ETS_CUEBANNER 8

#define EBS_NORMAL 1
#define EBS_HOT 2
#define EBS_DISABLED 3
#define EBS_FOCUSED 4
#define EBS_READONLY 5
#define EBS_ASSIST 6

#define EBWBS_NORMAL 1
#define EBWBS_HOT 2
#define EBWBS_DISABLED 3
#define EBWBS_FOCUSED 4

#define EPSN_NORMAL 1
#define EPSN_HOT 2
#define EPSN_FOCUSED 3
#define EPSN_DISABLED 4

#define EPSH_NORMAL 1
#define EPSH_HOT 2
#define EPSH_FOCUSED 3
#define EPSH_DISABLED 4

#define EPSV_NORMAL 1
#define EPSV_HOT 2
#define EPSV_FOCUSED 3
#define EPSV_DISABLED 4

#define EPSHV_NORMAL 1
#define EPSHV_HOT 2
#define EPSHV_FOCUSED 3
#define EPSHV_DISABLED 4


//
//  EXPLORERBARSTYLE class parts and states 
//
#define VSCLASS_EXPLORERBARSTYLE	L"EXPLORERBARSTYLE"
#define VSCLASS_EXPLORERBAR	L"EXPLORERBAR"

#define EBP_HEADERBACKGROUND 1
#define EBP_HEADERCLOSE 2
#define EBP_HEADERPIN 3
#define EBP_IEBARMENU 4
#define EBP_NORMALGROUPBACKGROUND 5
#define EBP_NORMALGROUPCOLLAPSE 6
#define EBP_NORMALGROUPEXPAND 7
#define EBP_NORMALGROUPHEAD 8
#define EBP_SPECIALGROUPBACKGROUND 9
#define EBP_SPECIALGROUPCOLLAPSE 10
#define EBP_SPECIALGROUPEXPAND 11
#define EBP_SPECIALGROUPHEAD 12

#define EXPLORERBARSTYLEPARTS EXPLORERBARPARTS;

#define EBHC_NORMAL 1
#define EBHC_HOT 2
#define EBHC_PRESSED 3

#define EBHP_NORMAL 1
#define EBHP_HOT 2
#define EBHP_PRESSED 3
#define EBHP_SELECTEDNORMAL 4
#define EBHP_SELECTEDHOT 5
#define EBHP_SELECTEDPRESSED 6

#define EBM_NORMAL 1
#define EBM_HOT 2
#define EBM_PRESSED 3

#define EBNGC_NORMAL 1
#define EBNGC_HOT 2
#define EBNGC_PRESSED 3

#define EBNGE_NORMAL 1
#define EBNGE_HOT 2
#define EBNGE_PRESSED 3

#define EBSGC_NORMAL 1
#define EBSGC_HOT 2
#define EBSGC_PRESSED 3

#define EBSGE_NORMAL 1
#define EBSGE_HOT 2
#define EBSGE_PRESSED 3


//
//  FLYOUTSTYLE class parts and states 
//
#define VSCLASS_FLYOUTSTYLE	L"FLYOUTSTYLE"
#define VSCLASS_FLYOUT	L"FLYOUT"

#define FLYOUT_HEADER 1
#define FLYOUT_BODY 2
#define FLYOUT_LABEL 3
#define FLYOUT_LINK 4
#define FLYOUT_DIVIDER 5
#define FLYOUT_WINDOW 6
#define FLYOUT_LINKAREA 7
#define FLYOUT_LINKHEADER 8

#define FLYOUTSTYLEPARTS FLYOUTPARTS;

#define FLS_NORMAL 1
#define FLS_SELECTED 2
#define FLS_EMPHASIZED 3
#define FLS_DISABLED 4

#define FLYOUTLINK_NORMAL 1
#define FLYOUTLINK_HOVER 2

#define FBS_NORMAL 1
#define FBS_EMPHASIZED 2

#define FLH_NORMAL 1
#define FLH_HOVER 2


//
//  HEADERSTYLE class parts and states 
//
#define VSCLASS_HEADERSTYLE	L"HEADERSTYLE"
#define VSCLASS_HEADER	L"HEADER"

#define HP_HEADERITEM 1
#define HP_HEADERITEMLEFT 2
#define HP_HEADERITEMRIGHT 3
#define HP_HEADERSORTARROW 4
#define HP_HEADERDROPDOWN 5
#define HP_HEADERDROPDOWNFILTER 6
#define HP_HEADEROVERFLOW 7

#define HEADERSTYLEPARTS HEADERPARTS;

#define HBG_DETAILS 1
#define HBG_ICON 2

#define HIS_NORMAL 1
#define HIS_HOT 2
#define HIS_PRESSED 3
#define HIS_SORTEDNORMAL 4
#define HIS_SORTEDHOT 5
#define HIS_SORTEDPRESSED 6
#define HIS_ICONNORMAL 7
#define HIS_ICONHOT 8
#define HIS_ICONPRESSED 9
#define HIS_ICONSORTEDNORMAL 10
#define HIS_ICONSORTEDHOT 11
#define HIS_ICONSORTEDPRESSED 12

#define HILS_NORMAL 1
#define HILS_HOT 2
#define HILS_PRESSED 3

#define HIRS_NORMAL 1
#define HIRS_HOT 2
#define HIRS_PRESSED 3

#define HSAS_SORTEDUP 1
#define HSAS_SORTEDDOWN 2

#define HDDS_NORMAL 1
#define HDDS_SOFTHOT 2
#define HDDS_HOT 3

#define HDDFS_NORMAL 1
#define HDDFS_SOFTHOT 2
#define HDDFS_HOT 3

#define HOFS_NORMAL 1
#define HOFS_HOT 2


//
//  LISTBOXSTYLE class parts and states 
//
#define VSCLASS_LISTBOXSTYLE	L"LISTBOXSTYLE"
#define VSCLASS_LISTBOX	L"LISTBOX"

#define LBCP_BORDER_HSCROLL 1
#define LBCP_BORDER_HVSCROLL 2
#define LBCP_BORDER_NOSCROLL 3
#define LBCP_BORDER_VSCROLL 4
#define LBCP_ITEM 5

#define LISTBOXSTYLEPARTS LISTBOXPARTS;

#define LBPSH_NORMAL 1
#define LBPSH_FOCUSED 2
#define LBPSH_HOT 3
#define LBPSH_DISABLED 4

#define LBPSHV_NORMAL 1
#define LBPSHV_FOCUSED 2
#define LBPSHV_HOT 3
#define LBPSHV_DISABLED 4

#define LBPSN_NORMAL 1
#define LBPSN_FOCUSED 2
#define LBPSN_HOT 3
#define LBPSN_DISABLED 4

#define LBPSV_NORMAL 1
#define LBPSV_FOCUSED 2
#define LBPSV_HOT 3
#define LBPSV_DISABLED 4

#define LBPSI_HOT 1
#define LBPSI_HOTSELECTED 2
#define LBPSI_SELECTED 3
#define LBPSI_SELECTEDNOTFOCUS 4


//
//  LISTVIEWSTYLE class parts and states 
//
#define VSCLASS_LISTVIEWSTYLE	L"LISTVIEWSTYLE"
#define VSCLASS_LISTVIEW	L"LISTVIEW"

#define LVP_LISTITEM 1
#define LVP_LISTGROUP 2
#define LVP_LISTDETAIL 3
#define LVP_LISTSORTEDDETAIL 4
#define LVP_EMPTYTEXT 5
#define LVP_GROUPHEADER 6
#define LVP_GROUPHEADERLINE 7
#define LVP_EXPANDBUTTON 8
#define LVP_COLLAPSEBUTTON 9
#define LVP_COLUMNDETAIL 10

#define LISTVIEWSTYLEPARTS LISTVIEWPARTS;

#define LISS_NORMAL 1
#define LISS_HOT 2
#define LISS_SELECTED 3
#define LISS_DISABLED 4
#define LISS_SELECTEDNOTFOCUS 5
#define LISS_HOTSELECTED 6

#define LVGH_OPEN 1
#define LVGH_OPENHOT 2
#define LVGH_OPENSELECTED 3
#define LVGH_OPENSELECTEDHOT 4
#define LVGH_OPENSELECTEDNOTFOCUSED 5
#define LVGH_OPENSELECTEDNOTFOCUSEDHOT 6
#define LVGH_OPENMIXEDSELECTION 7
#define LVGH_OPENMIXEDSELECTIONHOT 8
#define LVGH_CLOSE 9
#define LVGH_CLOSEHOT 10
#define LVGH_CLOSESELECTED 11
#define LVGH_CLOSESELECTEDHOT 12
#define LVGH_CLOSESELECTEDNOTFOCUSED 13
#define LVGH_CLOSESELECTEDNOTFOCUSEDHOT 14
#define LVGH_CLOSEMIXEDSELECTION 15
#define LVGH_CLOSEMIXEDSELECTIONHOT 16

#define LVGHL_OPEN 1
#define LVGHL_OPENHOT 2
#define LVGHL_OPENSELECTED 3
#define LVGHL_OPENSELECTEDHOT 4
#define LVGHL_OPENSELECTEDNOTFOCUSED 5
#define LVGHL_OPENSELECTEDNOTFOCUSEDHOT 6
#define LVGHL_OPENMIXEDSELECTION 7
#define LVGHL_OPENMIXEDSELECTIONHOT 8
#define LVGHL_CLOSE 9
#define LVGHL_CLOSEHOT 10
#define LVGHL_CLOSESELECTED 11
#define LVGHL_CLOSESELECTEDHOT 12
#define LVGHL_CLOSESELECTEDNOTFOCUSED 13
#define LVGHL_CLOSESELECTEDNOTFOCUSEDHOT 14
#define LVGHL_CLOSEMIXEDSELECTION 15
#define LVGHL_CLOSEMIXEDSELECTIONHOT 16

#define LVEB_NORMAL 1
#define LVEB_HOVER 2
#define LVEB_PUSHED 3

#define LVCB_NORMAL 1
#define LVCB_HOVER 2
#define LVCB_PUSHED 3


//
//  MENUSTYLE class parts and states 
//
#define VSCLASS_MENUSTYLE	L"MENUSTYLE"
#define VSCLASS_MENU	L"MENU"

#define MENU_MENUITEM_TMSCHEMA 1
#define MENU_MENUDROPDOWN_TMSCHEMA 2
#define MENU_MENUBARITEM_TMSCHEMA 3
#define MENU_MENUBARDROPDOWN_TMSCHEMA 4
#define MENU_CHEVRON_TMSCHEMA 5
#define MENU_SEPARATOR_TMSCHEMA 6
#define MENU_BARBACKGROUND 7
#define MENU_BARITEM 8
#define MENU_POPUPBACKGROUND 9
#define MENU_POPUPBORDERS 10
#define MENU_POPUPCHECK 11
#define MENU_POPUPCHECKBACKGROUND 12
#define MENU_POPUPGUTTER 13
#define MENU_POPUPITEM 14
#define MENU_POPUPSEPARATOR 15
#define MENU_POPUPSUBMENU 16
#define MENU_SYSTEMCLOSE 17
#define MENU_SYSTEMMAXIMIZE 18
#define MENU_SYSTEMMINIMIZE 19
#define MENU_SYSTEMRESTORE 20

#define MENUSTYLEPARTS MENUPARTS;

#define MB_ACTIVE 1
#define MB_INACTIVE 2

#define MBI_NORMAL 1
#define MBI_HOT 2
#define MBI_PUSHED 3
#define MBI_DISABLED 4
#define MBI_DISABLEDHOT 5
#define MBI_DISABLEDPUSHED 6

#define MC_CHECKMARKNORMAL 1
#define MC_CHECKMARKDISABLED 2
#define MC_BULLETNORMAL 3
#define MC_BULLETDISABLED 4

#define MCB_DISABLED 1
#define MCB_NORMAL 2
#define MCB_BITMAP 3

#define MPI_NORMAL 1
#define MPI_HOT 2
#define MPI_DISABLED 3
#define MPI_DISABLEDHOT 4

#define MSM_NORMAL 1
#define MSM_DISABLED 2

#define MSYSC_NORMAL 1
#define MSYSC_DISABLED 2

#define MSYSMX_NORMAL 1
#define MSYSMX_DISABLED 2

#define MSYSMN_NORMAL 1
#define MSYSMN_DISABLED 2

#define MSYSR_NORMAL 1
#define MSYSR_DISABLED 2


//
//  NAVIGATION class parts and states 
//
#define VSCLASS_NAVIGATION	L"NAVIGATION"

#define NAV_BACKBUTTON 1
#define NAV_FORWARDBUTTON 2
#define NAV_MENUBUTTON 3

#define NAV_BB_NORMAL 1
#define NAV_BB_HOT 2
#define NAV_BB_PRESSED 3
#define NAV_BB_DISABLED 4

#define NAV_FB_NORMAL 1
#define NAV_FB_HOT 2
#define NAV_FB_PRESSED 3
#define NAV_FB_DISABLED 4

#define NAV_MB_NORMAL 1
#define NAV_MB_HOT 2
#define NAV_MB_PRESSED 3
#define NAV_MB_DISABLED 4


//
//  PROGRESSSTYLE class parts and states 
//
#define VSCLASS_PROGRESSSTYLE	L"PROGRESSSTYLE"
#define VSCLASS_PROGRESS	L"PROGRESS"

#define PP_BAR 1
#define PP_BARVERT 2
#define PP_CHUNK 3
#define PP_CHUNKVERT 4
#define PP_FILL 5
#define PP_FILLVERT 6
#define PP_PULSEOVERLAY 7
#define PP_MOVEOVERLAY 8
#define PP_PULSEOVERLAYVERT 9
#define PP_MOVEOVERLAYVERT 10
#define PP_TRANSPARENTBAR 11
#define PP_TRANSPARENTBARVERT 12

#define PROGRESSSTYLEPARTS PROGRESSPARTS;

#define PBBS_NORMAL 1
#define PBBS_PARTIAL 2

#define PBBVS_NORMAL 1
#define PBBVS_PARTIAL 2

#define PBFS_NORMAL 1
#define PBFS_ERROR 2
#define PBFS_PAUSED 3
#define PBFS_PARTIAL 4

#define PBFVS_NORMAL 1
#define PBFVS_ERROR 2
#define PBFVS_PAUSED 3
#define PBFVS_PARTIAL 4


//
//  REBARSTYLE class parts and states 
//
#define VSCLASS_REBARSTYLE	L"REBARSTYLE"
#define VSCLASS_REBAR	L"REBAR"

#define RP_GRIPPER 1
#define RP_GRIPPERVERT 2
#define RP_BAND 3
#define RP_CHEVRON 4
#define RP_CHEVRONVERT 5
#define RP_BACKGROUND 6
#define RP_SPLITTER 7
#define RP_SPLITTERVERT 8

#define REBARSTYLEPARTS REBARPARTS;

#define CHEVS_NORMAL 1
#define CHEVS_HOT 2
#define CHEVS_PRESSED 3

#define CHEVSV_NORMAL 1
#define CHEVSV_HOT 2
#define CHEVSV_PRESSED 3

#define SPLITS_NORMAL 1
#define SPLITS_HOT 2
#define SPLITS_PRESSED 3

#define SPLITSV_NORMAL 1
#define SPLITSV_HOT 2
#define SPLITSV_PRESSED 3


//
//  SCROLLBARSTYLE class parts and states 
//
#define VSCLASS_SCROLLBARSTYLE	L"SCROLLBARSTYLE"
#define VSCLASS_SCROLLBAR	L"SCROLLBAR"

#define SBP_ARROWBTN 1
#define SBP_THUMBBTNHORZ 2
#define SBP_THUMBBTNVERT 3
#define SBP_LOWERTRACKHORZ 4
#define SBP_UPPERTRACKHORZ 5
#define SBP_LOWERTRACKVERT 6
#define SBP_UPPERTRACKVERT 7
#define SBP_GRIPPERHORZ 8
#define SBP_GRIPPERVERT 9
#define SBP_SIZEBOX 10

#define SCROLLBARSTYLEPARTS SCROLLBARPARTS;

#define ABS_UPNORMAL 1
#define ABS_UPHOT 2
#define ABS_UPPRESSED 3
#define ABS_UPDISABLED 4
#define ABS_DOWNNORMAL 5
#define ABS_DOWNHOT 6
#define ABS_DOWNPRESSED 7
#define ABS_DOWNDISABLED 8
#define ABS_LEFTNORMAL 9
#define ABS_LEFTHOT 10
#define ABS_LEFTPRESSED 11
#define ABS_LEFTDISABLED 12
#define ABS_RIGHTNORMAL 13
#define ABS_RIGHTHOT 14
#define ABS_RIGHTPRESSED 15
#define ABS_RIGHTDISABLED 16
#define ABS_UPHOVER 17
#define ABS_DOWNHOVER 18
#define ABS_LEFTHOVER 19
#define ABS_RIGHTHOVER 20

#define SCRBS_NORMAL 1
#define SCRBS_HOT 2
#define SCRBS_PRESSED 3
#define SCRBS_DISABLED 4
#define SCRBS_HOVER 5

#define SZB_RIGHTALIGN 1
#define SZB_LEFTALIGN 2
#define SZB_TOPRIGHTALIGN 3
#define SZB_TOPLEFTALIGN 4
#define SZB_HALFBOTTOMRIGHTALIGN 5
#define SZB_HALFBOTTOMLEFTALIGN 6
#define SZB_HALFTOPRIGHTALIGN 7
#define SZB_HALFTOPLEFTALIGN 8


//
//  SPINSTYLE class parts and states 
//
#define VSCLASS_SPINSTYLE	L"SPINSTYLE"
#define VSCLASS_SPIN	L"SPIN"

#define SPNP_UP 1
#define SPNP_DOWN 2
#define SPNP_UPHORZ 3
#define SPNP_DOWNHORZ 4

#define SPINSTYLEPARTS SPINPARTS;

#define UPS_NORMAL 1
#define UPS_HOT 2
#define UPS_PRESSED 3
#define UPS_DISABLED 4

#define DNS_NORMAL 1
#define DNS_HOT 2
#define DNS_PRESSED 3
#define DNS_DISABLED 4

#define UPHZS_NORMAL 1
#define UPHZS_HOT 2
#define UPHZS_PRESSED 3
#define UPHZS_DISABLED 4

#define DNHZS_NORMAL 1
#define DNHZS_HOT 2
#define DNHZS_PRESSED 3
#define DNHZS_DISABLED 4


//
//  STATUSSTYLE class parts and states 
//
#define VSCLASS_STATUSSTYLE	L"STATUSSTYLE"
#define VSCLASS_STATUS	L"STATUS"

#define SP_PANE 1
#define SP_GRIPPERPANE 2
#define SP_GRIPPER 3

#define STATUSSTYLEPARTS STATUSPARTS;


//
//  TABSTYLE class parts and states 
//
#define VSCLASS_TABSTYLE	L"TABSTYLE"
#define VSCLASS_TAB	L"TAB"

#define TABP_TABITEM 1
#define TABP_TABITEMLEFTEDGE 2
#define TABP_TABITEMRIGHTEDGE 3
#define TABP_TABITEMBOTHEDGE 4
#define TABP_TOPTABITEM 5
#define TABP_TOPTABITEMLEFTEDGE 6
#define TABP_TOPTABITEMRIGHTEDGE 7
#define TABP_TOPTABITEMBOTHEDGE 8
#define TABP_PANE 9
#define TABP_BODY 10
#define TABP_AEROWIZARDBODY 11

#define TABSTYLEPARTS TABPARTS;

#define TIS_NORMAL 1
#define TIS_HOT 2
#define TIS_SELECTED 3
#define TIS_DISABLED 4
#define TIS_FOCUSED 5

#define TILES_NORMAL 1
#define TILES_HOT 2
#define TILES_SELECTED 3
#define TILES_DISABLED 4
#define TILES_FOCUSED 5

#define TIRES_NORMAL 1
#define TIRES_HOT 2
#define TIRES_SELECTED 3
#define TIRES_DISABLED 4
#define TIRES_FOCUSED 5

#define TIBES_NORMAL 1
#define TIBES_HOT 2
#define TIBES_SELECTED 3
#define TIBES_DISABLED 4
#define TIBES_FOCUSED 5

#define TTIS_NORMAL 1
#define TTIS_HOT 2
#define TTIS_SELECTED 3
#define TTIS_DISABLED 4
#define TTIS_FOCUSED 5

#define TTILES_NORMAL 1
#define TTILES_HOT 2
#define TTILES_SELECTED 3
#define TTILES_DISABLED 4
#define TTILES_FOCUSED 5

#define TTIRES_NORMAL 1
#define TTIRES_HOT 2
#define TTIRES_SELECTED 3
#define TTIRES_DISABLED 4
#define TTIRES_FOCUSED 5

#define TTIBES_NORMAL 1
#define TTIBES_HOT 2
#define TTIBES_SELECTED 3
#define TTIBES_DISABLED 4
#define TTIBES_FOCUSED 5


//
//  TASKDIALOGSTYLE class parts and states 
//
#define VSCLASS_TASKDIALOGSTYLE	L"TASKDIALOGSTYLE"
#define VSCLASS_TASKDIALOG	L"TASKDIALOG"

#define TDLG_PRIMARYPANEL 1
#define TDLG_MAININSTRUCTIONPANE 2
#define TDLG_MAINICON 3
#define TDLG_CONTENTPANE 4
#define TDLG_CONTENTICON 5
#define TDLG_EXPANDEDCONTENT 6
#define TDLG_COMMANDLINKPANE 7
#define TDLG_SECONDARYPANEL 8
#define TDLG_CONTROLPANE 9
#define TDLG_BUTTONSECTION 10
#define TDLG_BUTTONWRAPPER 11
#define TDLG_EXPANDOTEXT 12
#define TDLG_EXPANDOBUTTON 13
#define TDLG_VERIFICATIONTEXT 14
#define TDLG_FOOTNOTEPANE 15
#define TDLG_FOOTNOTEAREA 16
#define TDLG_FOOTNOTESEPARATOR 17
#define TDLG_EXPANDEDFOOTERAREA 18
#define TDLG_PROGRESSBAR 19
#define TDLG_IMAGEALIGNMENT 20
#define TDLG_RADIOBUTTONPANE 21

#define TASKDIALOGSTYLEPARTS TASKDIALOGPARTS;

#define TDLGCPS_STANDALONE 1

#define TDLGEBS_NORMAL 1
#define TDLGEBS_HOVER 2
#define TDLGEBS_PRESSED 3
#define TDLGEBS_EXPANDEDNORMAL 4
#define TDLGEBS_EXPANDEDHOVER 5
#define TDLGEBS_EXPANDEDPRESSED 6


//
//  TEXTSTYLE class parts and states 
//
#define VSCLASS_TEXTSTYLE	L"TEXTSTYLE"

#define TEXT_MAININSTRUCTION 1
#define TEXT_INSTRUCTION 2
#define TEXT_BODYTITLE 3
#define TEXT_BODYTEXT 4
#define TEXT_SECONDARYTEXT 5
#define TEXT_HYPERLINKTEXT 6
#define TEXT_EXPANDED 7
#define TEXT_LABEL 8
#define TEXT_CONTROLLABEL 9

#define TS_HYPERLINK_NORMAL 1
#define TS_HYPERLINK_HOT 2
#define TS_HYPERLINK_PRESSED 3
#define TS_HYPERLINK_DISABLED 4

#define TS_CONTROLLABEL_NORMAL 1
#define TS_CONTROLLABEL_DISABLED 2


//
//  TOOLBARSTYLE class parts and states 
//
#define VSCLASS_TOOLBARSTYLE	L"TOOLBARSTYLE"
#define VSCLASS_TOOLBAR	L"TOOLBAR"

#define TP_BUTTON 1
#define TP_DROPDOWNBUTTON 2
#define TP_SPLITBUTTON 3
#define TP_SPLITBUTTONDROPDOWN 4
#define TP_SEPARATOR 5
#define TP_SEPARATORVERT 6
#define TP_DROPDOWNBUTTONGLYPH 7

#define TOOLBARSTYLEPARTS TOOLBARPARTS;

#define TS_NORMAL 1
#define TS_HOT 2
#define TS_PRESSED 3
#define TS_DISABLED 4
#define TS_CHECKED 5
#define TS_HOTCHECKED 6
#define TS_NEARHOT 7
#define TS_OTHERSIDEHOT 8


//
//  TOOLTIPSTYLE class parts and states 
//
#define VSCLASS_TOOLTIPSTYLE	L"TOOLTIPSTYLE"
#define VSCLASS_TOOLTIP	L"TOOLTIP"

#define TTP_STANDARD 1
#define TTP_STANDARDTITLE 2
#define TTP_BALLOON 3
#define TTP_BALLOONTITLE 4
#define TTP_CLOSE 5
#define TTP_BALLOONSTEM 6
#define TTP_WRENCH 7

#define TOOLTIPSTYLEPARTS TOOLTIPPARTS;

#define TTCS_NORMAL 1
#define TTCS_HOT 2
#define TTCS_PRESSED 3

#define TTSS_NORMAL 1
#define TTSS_LINK 2

#define TTBS_NORMAL 1
#define TTBS_LINK 2

#define TTBSS_POINTINGUPLEFTWALL 1
#define TTBSS_POINTINGUPCENTERED 2
#define TTBSS_POINTINGUPRIGHTWALL 3
#define TTBSS_POINTINGDOWNRIGHTWALL 4
#define TTBSS_POINTINGDOWNCENTERED 5
#define TTBSS_POINTINGDOWNLEFTWALL 6

#define TTWS_NORMAL 1
#define TTWS_HOT 2
#define TTWS_PRESSED 3


//
//  TRACKBARSTYLE class parts and states 
//
#define VSCLASS_TRACKBARSTYLE	L"TRACKBARSTYLE"
#define VSCLASS_TRACKBAR	L"TRACKBAR"

#define TKP_TRACK 1
#define TKP_TRACKVERT 2
#define TKP_THUMB 3
#define TKP_THUMBBOTTOM 4
#define TKP_THUMBTOP 5
#define TKP_THUMBVERT 6
#define TKP_THUMBLEFT 7
#define TKP_THUMBRIGHT 8
#define TKP_TICS 9
#define TKP_TICSVERT 10

#define TRACKBARSTYLEPARTS TRACKBARPARTS;

#define TKS_NORMAL 1

#define TRS_NORMAL 1

#define TRVS_NORMAL 1

#define TUS_NORMAL 1
#define TUS_HOT 2
#define TUS_PRESSED 3
#define TUS_FOCUSED 4
#define TUS_DISABLED 5

#define TUBS_NORMAL 1
#define TUBS_HOT 2
#define TUBS_PRESSED 3
#define TUBS_FOCUSED 4
#define TUBS_DISABLED 5

#define TUTS_NORMAL 1
#define TUTS_HOT 2
#define TUTS_PRESSED 3
#define TUTS_FOCUSED 4
#define TUTS_DISABLED 5

#define TUVS_NORMAL 1
#define TUVS_HOT 2
#define TUVS_PRESSED 3
#define TUVS_FOCUSED 4
#define TUVS_DISABLED 5

#define TUVLS_NORMAL 1
#define TUVLS_HOT 2
#define TUVLS_PRESSED 3
#define TUVLS_FOCUSED 4
#define TUVLS_DISABLED 5

#define TUVRS_NORMAL 1
#define TUVRS_HOT 2
#define TUVRS_PRESSED 3
#define TUVRS_FOCUSED 4
#define TUVRS_DISABLED 5

#define TSS_NORMAL 1

#define TSVS_NORMAL 1


//
//  TREEVIEWSTYLE class parts and states 
//
#define VSCLASS_TREEVIEWSTYLE	L"TREEVIEWSTYLE"
#define VSCLASS_TREEVIEW	L"TREEVIEW"

#define TVP_TREEITEM 1
#define TVP_GLYPH 2
#define TVP_BRANCH 3
#define TVP_HOTGLYPH 4

#define TREEVIEWSTYLEPARTS TREEVIEWPARTS;

#define TREIS_NORMAL 1
#define TREIS_HOT 2
#define TREIS_SELECTED 3
#define TREIS_DISABLED 4
#define TREIS_SELECTEDNOTFOCUS 5
#define TREIS_HOTSELECTED 6

#define GLPS_CLOSED 1
#define GLPS_OPENED 2

#define HGLPS_CLOSED 1
#define HGLPS_OPENED 2


//
//  WINDOWSTYLE class parts and states 
//
#define VSCLASS_WINDOWSTYLE	L"WINDOWSTYLE"
#define VSCLASS_WINDOW	L"WINDOW"

#define WP_CAPTION 1
#define WP_SMALLCAPTION 2
#define WP_MINCAPTION 3
#define WP_SMALLMINCAPTION 4
#define WP_MAXCAPTION 5
#define WP_SMALLMAXCAPTION 6
#define WP_FRAMELEFT 7
#define WP_FRAMERIGHT 8
#define WP_FRAMEBOTTOM 9
#define WP_SMALLFRAMELEFT 10
#define WP_SMALLFRAMERIGHT 11
#define WP_SMALLFRAMEBOTTOM 12
#define WP_SYSBUTTON 13
#define WP_MDISYSBUTTON 14
#define WP_MINBUTTON 15
#define WP_MDIMINBUTTON 16
#define WP_MAXBUTTON 17
#define WP_CLOSEBUTTON 18
#define WP_SMALLCLOSEBUTTON 19
#define WP_MDICLOSEBUTTON 20
#define WP_RESTOREBUTTON 21
#define WP_MDIRESTOREBUTTON 22
#define WP_HELPBUTTON 23
#define WP_MDIHELPBUTTON 24
#define WP_HORZSCROLL 25
#define WP_HORZTHUMB 26
#define WP_VERTSCROLL 27
#define WP_VERTTHUMB 28
#define WP_DIALOG 29
#define WP_CAPTIONSIZINGTEMPLATE 30
#define WP_SMALLCAPTIONSIZINGTEMPLATE 31
#define WP_FRAMELEFTSIZINGTEMPLATE 32
#define WP_SMALLFRAMELEFTSIZINGTEMPLATE 33
#define WP_FRAMERIGHTSIZINGTEMPLATE 34
#define WP_SMALLFRAMERIGHTSIZINGTEMPLATE 35
#define WP_FRAMEBOTTOMSIZINGTEMPLATE 36
#define WP_SMALLFRAMEBOTTOMSIZINGTEMPLATE 37
#define WP_FRAME 38

#define WINDOWSTYLEPARTS WINDOWPARTS;

#define FS_ACTIVE 1
#define FS_INACTIVE 2

#define CS_ACTIVE 1
#define CS_INACTIVE 2
#define CS_DISABLED 3

#define MXCS_ACTIVE 1
#define MXCS_INACTIVE 2
#define MXCS_DISABLED 3

#define MNCS_ACTIVE 1
#define MNCS_INACTIVE 2
#define MNCS_DISABLED 3

#define HSS_NORMAL 1
#define HSS_HOT 2
#define HSS_PUSHED 3
#define HSS_DISABLED 4

#define HTS_NORMAL 1
#define HTS_HOT 2
#define HTS_PUSHED 3
#define HTS_DISABLED 4

#define VSS_NORMAL 1
#define VSS_HOT 2
#define VSS_PUSHED 3
#define VSS_DISABLED 4

#define VTS_NORMAL 1
#define VTS_HOT 2
#define VTS_PUSHED 3
#define VTS_DISABLED 4

#define SBS_NORMAL 1
#define SBS_HOT 2
#define SBS_PUSHED 3
#define SBS_DISABLED 4

#define MINBS_NORMAL 1
#define MINBS_HOT 2
#define MINBS_PUSHED 3
#define MINBS_DISABLED 4

#define MAXBS_NORMAL 1
#define MAXBS_HOT 2
#define MAXBS_PUSHED 3
#define MAXBS_DISABLED 4

#define RBS_NORMAL 1
#define RBS_HOT 2
#define RBS_PUSHED 3
#define RBS_DISABLED 4

#define HBS_NORMAL 1
#define HBS_HOT 2
#define HBS_PUSHED 3
#define HBS_DISABLED 4

#define CBS_NORMAL 1
#define CBS_HOT 2
#define CBS_PUSHED 3
#define CBS_DISABLED 4
